// Warlock e Mago (SRD 5.2.1). Il Warlock ha slot del Patto (pactSlots) e un elenco di Suppliche occulte; il Mago ha il libro degli incantesimi.
import { asi, B, epicBoon, f, opt, slotCols, subclassFeature, type ClassDef } from "./class-types";

const grant = (spell: string, extra: Record<string, unknown> = {}) => ({ op: "grantSpell", spell, mode: "alwaysPrepared", ...extra });
const byLevel = (rows: [number, string[]][], cls: string) => rows.flatMap(([lv, sp]) => sp.map((s) => grant(s, { when: `classLevel:${cls}>=${lv}` })));
const lvl = (n: number) => `classLevel:warlock>=${n}`;
const INV = (id: string, it: string, en: string, dIt: string, dEn: string, requires?: string) => opt(id, [it, en], [dIt, dEn], requires ? { requires } : {});

// Suppliche occulte: il prerequisito di livello e di Patto è nella condizione; "un trucchetto che infligge danni" resta nel testo
const INVOCATIONS = [
  INV("armor_of_shadows", "Armatura delle ombre", "Armor of Shadows", "Puoi lanciare Armatura magica su te stesso senza slot.", "You can cast Mage Armor on yourself without a slot."),
  INV("otherworldly_leap", "Balzo ultraterreno", "Otherworldly Leap", "Puoi lanciare Saltare su te stesso senza slot.", "You can cast Jump on yourself without a slot.", lvl(2)),
  INV("lessons_of_the_first_ones", "Conoscenze degli Antichi", "Lessons of the First Ones", "Ottieni un talento Origini a scelta. Ripetibile (talento diverso).", "You gain an Origin feat of your choice. Repeatable (different feat).", lvl(2)),
  INV("agonizing_blast", "Deflagrazione agonizzante", "Agonizing Blast", "Scegli un trucchetto da warlock che infligge danni: aggiungi Carisma ai suoi danni. Ripetibile (trucchetto diverso).", "Choose a Warlock cantrip that deals damage: add your Charisma modifier to its damage. Repeatable (different cantrip).", lvl(2)),
  INV("repelling_blast", "Deflagrazione respingente", "Repelling Blast", "Scegli un trucchetto con tiro per colpire: se colpisci una creatura Grande o più piccola puoi spingerla fino a 3 m. Ripetibile (trucchetto diverso).", "Choose a cantrip that uses an attack roll: when you hit a Large or smaller creature you can push it up to 10 feet. Repeatable (different cantrip).", lvl(2)),
  INV("gift_of_the_depths", "Dono degli abissi", "Gift of the Depths", "Respiri sott'acqua e hai velocità di nuoto pari alla tua; Respirare sott'acqua una volta per riposo lungo senza slot.", "You can breathe underwater and have a Swim Speed equal to your Speed; Water Breathing once per Long Rest without a slot.", lvl(5)),
  INV("gift_of_the_protectors", "Dono del protettore", "Gift of the Protectors", "Il Libro delle Ombre ha una pagina su cui le creature scrivono il proprio nome: la prima volta che una scende a 0 PF resta a 1 (una volta per riposo lungo).", "Your Book of Shadows has a page where creatures write their names: the first time one drops to 0 Hit Points it drops to 1 instead (once per Long Rest).", `${lvl(9)} && hasFeature:pact_of_the_tome`),
  INV("investment_of_the_chain_master", "Investitura del Signore delle Catene", "Investment of the Chain Master", "Il famiglio di Trova famiglio ottiene volo o nuoto 12 m, attacco rapido, danni necrotici o radiosi, la tua CD e resistenza a un danno (reazione).", "Your Find Familiar gains a 40-foot Fly or Swim Speed, a quick Attack, Necrotic or Radiant damage, your spell save DC, and Resistance to a damage (Reaction).", `${lvl(5)} && hasFeature:pact_of_the_chain`),
  INV("thirsting_blade", "Lama assetata", "Thirsting Blade", "Attacco extra solo con l'arma del patto: attacchi due volte con l'azione Attacco.", "Extra Attack with your pact weapon only: you attack twice with the Attack action.", `${lvl(5)} && hasFeature:pact_of_the_blade`),
  INV("devouring_blade", "Lama divoratrice", "Devouring Blade", "L'Attacco extra di Lama assetata dà due attacchi aggiuntivi invece di uno.", "The Extra Attack of Thirsting Blade grants two additional attacks instead of one.", `${lvl(12)} && hasFeature:thirsting_blade`),
  INV("eldritch_spear", "Lancia occulta", "Eldritch Spear", "Scegli un trucchetto che infligge danni con gittata di 3 m o più: la gittata aumenta di 9 m per ogni livello da warlock. Ripetibile (trucchetto diverso).", "Choose a damaging cantrip with a range of 10 feet or more: its range increases by 30 feet per Warlock level. Repeatable (different cantrip).", lvl(2)),
  INV("master_of_myriad_forms", "Maestro di mille forme", "Master of Myriad Forms", "Puoi lanciare Alterare se stesso senza slot.", "You can cast Alter Self without a slot.", lvl(5)),
  INV("mask_of_many_faces", "Maschera dei molti volti", "Mask of Many Faces", "Puoi lanciare Camuffare se stesso senza slot.", "You can cast Disguise Self without a slot.", lvl(2)),
  INV("eldritch_mind", "Mente occulta", "Eldritch Mind", "Vantaggio ai tiri salvezza su Costituzione per mantenere la concentrazione.", "Advantage on Constitution saves to maintain Concentration."),
  INV("ascendant_step", "Passo ascendente", "Ascendant Step", "Puoi lanciare Levitazione su te stesso senza slot.", "You can cast Levitate on yourself without a slot.", lvl(5)),
  INV("pact_of_the_chain", "Patto della catena", "Pact of the Chain", "Impari Trova famiglio e lo lanci come azione di Magia senza slot, con forme speciali (imp, pseudodrago, quasit, scheletro, sfinge della meraviglia, spiritello, serpente velenoso); un attacco del famiglio al posto di uno tuo.", "You learn Find Familiar and cast it as a Magic action without a slot, with special forms (Imp, Pseudodragon, Quasit, Skeleton, Sphinx of Wonder, Sprite, Venomous Snake); the familiar can attack in place of one of your attacks."),
  INV("pact_of_the_blade", "Patto della lama", "Pact of the Blade", "Azione bonus: evochi un'arma del patto (o leghi un'arma magica): hai competenza, la usi come focus, puoi usare Carisma per colpire e per i danni e scegliere il tipo di danno (necrotico, psichico, radioso o normale).", "Bonus Action: conjure a pact weapon (or bond a magic weapon): you're proficient, can use it as a focus, use Charisma for attack and damage, and choose its damage type (Necrotic, Psychic, Radiant, or normal)."),
  INV("pact_of_the_tome", "Patto del tomo", "Pact of the Tome", "Dopo un riposo breve o lungo evochi un Libro delle Ombre con tre trucchetti e due rituali di 1° livello di qualsiasi lista; sono preparati e valgono come da warlock; il libro è un focus.", "After a Short or Long Rest you conjure a Book of Shadows with three cantrips and two level 1 Ritual spells from any list; they're prepared and count as Warlock spells; the book is a focus."),
  INV("eldritch_smite", "Punizione occulta", "Eldritch Smite", "Una volta per turno, colpendo con l'arma del patto spendi uno slot del Patto: 1d8 danni da forza + 1d8 per livello dello slot; un bersaglio Enorme o più piccolo cade prono.", "Once per turn when you hit with your pact weapon, expend a Pact Magic slot: 1d8 Force damage plus 1d8 per slot level; a Huge or smaller target is knocked Prone.", `${lvl(5)} && hasFeature:pact_of_the_blade`),
  INV("gaze_of_two_minds", "Sguardo delle due menti", "Gaze of Two Minds", "Azione bonus: tocchi una creatura consenziente e percepisci con i suoi sensi; puoi mantenere il legame con azioni bonus e lanciare incantesimi dal suo spazio se entro 18 m.", "Bonus Action: touch a willing creature and perceive through its senses; you can maintain the link with Bonus Actions and cast spells from its space if within 60 feet.", lvl(5)),
  INV("lifedrinker", "Succhiavita", "Lifedrinker", "Una volta per turno, colpendo con l'arma del patto: +1d6 danni necrotici, psichici o radiosi; puoi spendere un Dado Vita per recuperare PF pari al tiro + Costituzione.", "Once per turn when you hit with your pact weapon: +1d6 Necrotic, Psychic, or Radiant damage; you can expend a Hit Point Die to regain Hit Points equal to the roll + Constitution.", `${lvl(9)} && hasFeature:pact_of_the_blade`),
  INV("whispers_of_the_grave", "Sussurri dalla tomba", "Whispers of the Grave", "Puoi lanciare Parlare con i morti senza slot.", "You can cast Speak with Dead without a slot.", lvl(7)),
  INV("one_with_shadows", "Tutt'uno con le ombre", "One with Shadows", "In oscurità o luce fioca puoi lanciare Invisibilità su te stesso senza slot.", "While in Dim Light or Darkness you can cast Invisibility on yourself without a slot.", lvl(5)),
  INV("fiendish_vigor", "Vigore immondo", "Fiendish Vigor", "Puoi lanciare Vita falsata su te stesso senza slot, ottenendo sempre il massimo dei PF temporanei.", "You can cast False Life on yourself without a slot, always gaining the maximum Temporary Hit Points.", lvl(2)),
  INV("visions_of_distant_realms", "Visione dei Reami Lontani", "Visions of Distant Realms", "Puoi lanciare Occhio arcano senza slot.", "You can cast Arcane Eye without a slot.", lvl(9)),
  INV("misty_visions", "Visioni velate", "Misty Visions", "Puoi lanciare Immagine silenziosa senza slot.", "You can cast Silent Image without a slot.", lvl(2)),
  INV("devils_sight", "Vista del diavolo", "Devil's Sight", "Vedi normalmente con luce fioca e oscurità, anche magica, entro 36 m.", "You can see normally in Dim Light and Darkness, including magical, out to 120 feet.", lvl(2)),
  INV("witch_sight", "Vista stregata", "Witch Sight", "Vista pura entro 9 m.", "You have Truesight out to 30 feet.", lvl(15)),
];

export const WARLOCK: ClassDef = {
  id: "warlock", name: B("Warlock", "Warlock"), hitDie: 8, primary: ["cha"], saves: ["wis", "cha"],
  description: B("Incantatore legato a un patrono: Magia del patto con pochi slot potenti, Suppliche occulte e Arcanum mistico.", "A caster bound to a patron: Pact Magic with a few powerful slots, Eldritch Invocations, and Mystic Arcanum."),
  skills: { count: 2, from: ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"] },
  armor: ["light"], weapons: ["simple"], multiclass: { armor: ["light"] },
  multiclassPhrases: { it: ["Dado Vita e competenza nelle armature leggere"], en: ["Hit Point Die and training with Light armor"] },
  caster: { type: "pact", ability: "cha", list: "warlock" },
  checkPhrases: { it: INVOCATIONS.map((o) => (o.name as { it: string }).it), en: INVOCATIONS.map((o) => (o.name as { en: string }).en) },
  core: { primaryIt: "Carisma", primaryEn: "Charisma", savesIt: "Saggezza e Carisma", savesEn: "Wisdom and Charisma", skillsIt: "Due a scelta tra: Arcano, Indagare, Inganno, Intimidire, Natura, Religione o Storia", skillsEn: "Choose 2: Arcana, Deception, History, Intimidation, Investigation, Nature, or Religion",
    weaponsIt: "Armi semplici", weaponsEn: "Simple weapons", armorIt: "Armature leggere", armorEn: "Light armor" },
  equipment: {
    A: { gp: 15, items: [{ item: "leather_armor", it: "armatura di cuoio", en: "Leather Armor" }, { item: "sickle", it: "falcetto", en: "Sickle" }, { item: "dagger", qty: 2, it: "2 pugnali", en: "2 Daggers" }, { item: "arcane_focus_orb", it: "focus arcano (globo)", en: "Arcane Focus (orb)" }, { item: "book", it: "libro (scienze occulte)", en: "Book (occult lore)" }, { item: "scholars_pack", it: "dotazione da studioso", en: "Scholar's Pack" }] },
    B: { gp: 100, items: [] },
  },
  columns: [{ id: "invocations", name: B("Suppliche occulte", "Invocations") }, { id: "cantrips", name: B("Trucchetti", "Cantrips") }, { id: "prepared", name: B("Incantesimi preparati", "Prepared Spells") }, { id: "pact_slots", name: B("Slot incantesimo", "Spell Slots") }, { id: "pact_slot_level", name: B("Livello di slot", "Slot Level") }],
  features: [
    f(1, "eldritch_invocations", ["Suppliche occulte", "Eldritch Invocations"], ["Ottieni suppliche a scelta (colonna Suppliche occulte), ognuna con eventuali prerequisiti di livello o di Patto; a ogni livello da warlock puoi sostituirne una (non se è prerequisito di un'altra). Non si sceglie due volte la stessa, salvo dove indicato.", "You gain invocations of your choice (Invocations column), each with any level or Pact prerequisite; whenever you gain a Warlock level you can replace one (not one that's a prerequisite of another). You can't pick the same one twice unless noted."],
      { choices: [{ id: "warlock_invocations", label: B("Suppliche occulte", "Eldritch Invocations"), countFrom: "invocations", options: INVOCATIONS }] }),
    f(1, "pact_magic", ["Magia del patto", "Pact Magic"], ["Lanci incantesimi da warlock con Carisma, usando un focus arcano. Conosci 2 trucchetti (altri al 4° e 10°) e prepari incantesimi (colonna Incantesimi preparati) dalla lista del warlock, di livello non superiore a quello degli slot del Patto. Gli slot (tutti dello stesso livello, colonne Slot incantesimo e Livello di slot) tornano con un riposo breve o lungo.", "You cast Warlock spells using Charisma, with an Arcane Focus. You know 2 cantrips (more at levels 4 and 10) and prepare spells (Prepared Spells column) from the Warlock list, no higher than your Pact Magic slot level. Your slots (all the same level, Spell Slots and Slot Level columns) return after a Short or Long Rest."]),
    f(2, "magical_cunning", ["Scaltrezza magica", "Magical Cunning"], ["Con un rito di 1 minuto recuperi slot del Patto spesi fino a metà del massimo (per eccesso). Una volta per riposo lungo.", "With a 1-minute rite you regain expended Pact Magic slots up to half your maximum (rounded up). Once per Long Rest."], { usage: { uses: 1, recharge: "long_rest" } }),
    subclassFeature("warlock", "del warlock", "Warlock"),
    asi("warlock", 4, false), asi("warlock", 8), asi("warlock", 12), asi("warlock", 16),
    f(9, "contact_patron", ["Contatta patrono", "Contact Patron"], ["Contattare altri piani è sempre preparato: puoi lanciarlo senza slot (supera automaticamente il tiro salvezza), una volta per riposo lungo.", "Contact Other Plane is always prepared: you can cast it without a slot (you automatically succeed on its save), once per Long Rest."], { effects: [grant("contact_other_plane", { freeCast: { uses: 1, recharge: "long_rest" } })] }),
    f(11, "mystic_arcanum", ["Arcanum mistico", "Mystic Arcanum"], ["Scegli un incantesimo da warlock di 6° livello da lanciare una volta senza slot per riposo lungo. Altri arcanum al 13° (7° livello), 15° (8°) e 17° (9°); a ogni livello puoi sostituirne uno.", "Choose a level 6 Warlock spell to cast once without a slot per Long Rest. More arcana at levels 13 (level 7 spell), 15 (level 8), and 17 (level 9); whenever you gain a level you can replace one."],
      { row: B("Arcanum mistico (incantesimo di 6º livello)", "Mystic Arcanum (level 6 spell)"), usage: { uses: 1, recharge: "long_rest" }, choices: [{ id: "warlock_arcanum_6", label: B("Arcanum (6° livello)", "Arcanum (level 6)"), count: 1, source: "spells:warlock", filter: { level: 6 } }] }),
    f(13, "mystic_arcanum_7", ["Arcanum mistico", "Mystic Arcanum"], ["Incantesimo da warlock di 7° livello, una volta per riposo lungo.", "A level 7 Warlock spell, once per Long Rest."], { tableOnly: true, row: B("Arcanum mistico (incantesimo di 7º livello)", "Mystic Arcanum (level 7 spell)"), usage: { uses: 1, recharge: "long_rest" }, choices: [{ id: "warlock_arcanum_7", label: B("Arcanum (7° livello)", "Arcanum (level 7)"), count: 1, source: "spells:warlock", filter: { level: 7 } }] }),
    f(15, "mystic_arcanum_8", ["Arcanum mistico", "Mystic Arcanum"], ["Incantesimo da warlock di 8° livello, una volta per riposo lungo.", "A level 8 Warlock spell, once per Long Rest."], { tableOnly: true, row: B("Arcanum mistico (incantesimo di 8º livello)", "Mystic Arcanum (level 8 spell)"), usage: { uses: 1, recharge: "long_rest" }, choices: [{ id: "warlock_arcanum_8", label: B("Arcanum (8° livello)", "Arcanum (level 8)"), count: 1, source: "spells:warlock", filter: { level: 8 } }] }),
    f(17, "mystic_arcanum_9", ["Arcanum mistico", "Mystic Arcanum"], ["Incantesimo da warlock di 9° livello, una volta per riposo lungo.", "A level 9 Warlock spell, once per Long Rest."], { tableOnly: true, row: B("Arcanum mistico (incantesimo di 9º livello)", "Mystic Arcanum (level 9 spell)"), usage: { uses: 1, recharge: "long_rest" }, choices: [{ id: "warlock_arcanum_9", label: B("Arcanum (9° livello)", "Arcanum (level 9)"), count: 1, source: "spells:warlock", filter: { level: 9 } }] }),
    epicBoon("warlock", B("Dono del fato", "Boon of Fate")),
    f(20, "eldritch_master", ["Maestro dell'occulto", "Eldritch Master"], ["Usando Scaltrezza magica recuperi tutti gli slot del Patto spesi.", "When you use Magical Cunning you regain all expended Pact Magic slots."]),
  ],
  subclass: {
    id: "fiend", name: B("Patrono immondo", "Fiend Patron"), heading: B("Sottoclasse del warlock: Patrono immondo", "Warlock Subclass: Fiend Patron"),
    description: B("Un patto con i Piani Inferiori: punti ferita temporanei, incantesimi infernali, fortuna e Scagliare all'Inferno.", "A pact with the Lower Planes: Temporary Hit Points, fiery spells, luck, and Hurl Through Hell."),
    checkPhrases: { it: ["Comando, mani brucianti , raggio rovente , suggestione", "Nube maleodorante, palla di fuoco", "Muro di fuoco, scudo di fuoco", "Costrizione , piaga degli insetti"], en: ["Burning Hands, Command, Scorching Ray, Suggestion", "Fireball, Stinking Cloud", "Fire Shield, Wall of Fire", "Geas, Insect Plague"] },
    features: [
      f(3, "dark_ones_blessing", ["Benedizione dell'oscuro", "Dark One's Blessing"], ["Quando riduci un nemico a 0 PF (o lo fa qualcun altro entro 3 m da te) ottieni PF temporanei pari a Carisma + livello da warlock (minimo 1).", "When you reduce an enemy to 0 Hit Points (or an enemy within 10 feet of you drops to 0) you gain Temporary Hit Points equal to your Charisma modifier + Warlock level (minimum 1)."]),
      f(3, "fiend_spells", ["Incantesimi immondi", "Fiend Spells"], ["Incantesimi sempre preparati: 3° Comando, Mani brucianti, Raggio rovente, Suggestione; 5° Nube maleodorante, Palla di fuoco; 7° Muro di fuoco, Scudo di fuoco; 9° Costrizione, Piaga degli insetti.", "Always-prepared spells: level 3 Burning Hands, Command, Scorching Ray, Suggestion; 5 Fireball, Stinking Cloud; 7 Fire Shield, Wall of Fire; 9 Geas, Insect Plague."],
        { effects: byLevel([[3, ["command", "burning_hands", "scorching_ray", "suggestion"]], [5, ["stinking_cloud", "fireball"]], [7, ["wall_of_fire", "fire_shield"]], [9, ["geas", "insect_plague"]]], "warlock") }),
      f(6, "dark_ones_own_luck", ["Fortuna dell'Oscuro", "Dark One's Own Luck"], ["Dopo aver visto un tiro di una prova di caratteristica o di un tiro salvezza puoi aggiungere 1d10 (una volta per tiro). Usi pari a Carisma (minimo 1) per riposo lungo.", "After seeing the roll of an ability check or saving throw you can add 1d10 to it (once per roll). Uses equal your Charisma modifier (minimum 1) per Long Rest."], { usage: { uses: "max(1, mod:cha)", recharge: "long_rest" } }),
      f(10, "fiendish_resilience", ["Resilienza immonda", "Fiendish Resilience"], ["Dopo un riposo breve o lungo scegli un tipo di danno (tranne forza): hai resistenza finché non ne scegli un altro.", "After a Short or Long Rest choose a damage type (except Force): you have Resistance to it until you choose a different one."]),
      f(14, "hurl_through_hell", ["Scagliare all'Inferno", "Hurl Through Hell"], ["Una volta per turno, colpendo con un tiro per colpire puoi spedire il bersaglio nei Piani Inferiori: tiro salvezza su Carisma o, se non è un immondo, subisce 8d10 danni psichici ed è incapacitato fino alla fine del tuo turno successivo. Una volta per riposo lungo (o spendendo uno slot del Patto).", "Once per turn when you hit with an attack roll you can send the target to the Lower Planes: Charisma save or, if it isn't a Fiend, it takes 8d10 Psychic damage and is Incapacitated until the end of your next turn. Once per Long Rest (or by expending a Pact Magic slot)."], { usage: { uses: 1, recharge: "long_rest" } }),
    ],
  },
};

export const WIZARD: ClassDef = {
  id: "wizard", name: B("Mago", "Wizard"), hitDie: 6, primary: ["int"], saves: ["int", "wis"],
  description: B("Studioso della magia arcana: libro degli incantesimi, Recupero arcano e la più vasta lista di incantesimi.", "A scholar of arcane magic: a spellbook, Arcane Recovery, and the widest spell list."),
  skills: { count: 2, from: ["arcana", "history", "insight", "investigation", "medicine", "nature", "religion"] },
  armor: [], weapons: ["simple"], multiclass: {},
  multiclassPhrases: { it: ["Ottiene il Dado Vita dalla tabella Tratti del mago"], en: ["Gain the Hit Point Die from the Core Wizard Traits table"] },
  caster: { type: "full", ability: "int", list: "wizard", spellbook: true },
  core: { primaryIt: "Intelligenza", primaryEn: "Intelligence", savesIt: "Intelligenza e Saggezza", savesEn: "Intelligence and Wisdom", skillsIt: "Due a scelta tra: Arcano, Indagare, Intuizione, Medicina, Natura, Religione o Storia", skillsEn: "Choose 2: Arcana, History, Insight, Investigation, Medicine, Nature, or Religion",
    weaponsIt: "Armi semplici", weaponsEn: "Simple weapons", armorIt: "Nessuno", armorEn: "None" },
  equipment: {
    A: { gp: 5, items: [{ item: "dagger", qty: 2, it: "2 pugnali", en: "2 Daggers" }, { item: "arcane_focus_staff", it: "focus arcano (bastone ferrato)", en: "Arcane Focus (Quarterstaff)" }, { item: "robe", it: "veste", en: "Robe" }, { item: "$spellbook", it: "libro degli incantesimi", en: "Spellbook" }, { item: "scholars_pack", it: "dotazione da studioso", en: "Scholar's Pack" }] },
    B: { gp: 55, items: [] },
  },
  columns: [{ id: "cantrips", name: B("Trucchetti", "Cantrips") }, { id: "prepared", name: B("Incantesimi preparati", "Prepared Spells") }, ...slotCols(9)],
  features: [
    f(1, "spellcasting", ["Incantesimi", "Spellcasting"], ["Lanci incantesimi da mago con Intelligenza, usando un focus arcano o il libro. Conosci 3 trucchetti (altri al 4° e 10°; a ogni riposo lungo puoi cambiarne uno). Il libro degli incantesimi parte con 6 incantesimi di 1° livello (+2 a ogni livello); prepari incantesimi (colonna Incantesimi preparati) dal libro e dopo un riposo lungo puoi cambiarli. Gli slot tornano con un riposo lungo.", "You cast Wizard spells using Intelligence, with an Arcane Focus or your spellbook. You know 3 cantrips (more at levels 4 and 10; you can swap one after a Long Rest). Your spellbook starts with six level 1 spells (+2 each level); you prepare spells (Prepared Spells column) from the book and can change them after a Long Rest. Slots return after a Long Rest."]),
    f(1, "ritual_adept", ["Adepto dei rituali", "Ritual Adept"], ["Puoi lanciare come rituale qualsiasi incantesimo con descrittore rituale presente nel tuo libro, senza prepararlo (leggendo il libro).", "You can cast any spell with the Ritual tag from your spellbook as a Ritual without preparing it (by reading the book)."]),
    f(1, "arcane_recovery", ["Recupero arcano", "Arcane Recovery"], ["Dopo un riposo breve recuperi slot spesi di livello totale pari a metà del livello da mago (per eccesso), nessuno di 6° livello o superiore. Una volta per riposo lungo.", "After a Short Rest you recover expended slots with a combined level up to half your Wizard level (rounded up), none of level 6 or higher. Once per Long Rest."], { usage: { uses: 1, recharge: "long_rest" } }),
    f(2, "scholar", ["Studioso", "Scholar"], ["Ottieni Maestria in una abilità in cui hai competenza tra Arcano, Indagare, Medicina, Natura, Religione e Storia.", "You gain Expertise in one skill you're proficient in among Arcana, History, Investigation, Medicine, Nature, and Religion."],
      { choices: [{ id: "wizard_scholar", label: B("Maestria", "Expertise"), count: 1, options: ["arcana", "investigation", "medicine", "nature", "religion", "history"].map((id) => ({ id, name: { it: `$skill:${id}`, en: `$skill:${id}` }, effects: [{ op: "grantSkillProficiency", skills: [id], expertise: true }] })) }] }),
    subclassFeature("wizard", "del mago", "Wizard"),
    asi("wizard", 4, false), asi("wizard", 8), asi("wizard", 12), asi("wizard", 16),
    f(5, "memorize_spell", ["Memorizzare incantesimi", "Memorize Spell"], ["Con un riposo breve puoi studiare il libro e sostituire un incantesimo preparato di 1° livello o superiore con un altro dal libro.", "After a Short Rest you can study your spellbook and replace one prepared level 1+ spell with another from the book."]),
    f(18, "spell_mastery", ["Maestria negli incantesimi", "Spell Mastery"], ["Scegli dal libro un incantesimo di 1° e uno di 2° livello con tempo di lancio di 1 azione: sono sempre preparati e li lanci al livello più basso senza slot. Dopo un riposo lungo puoi cambiarne uno.", "Choose from your book a level 1 and a level 2 spell with a casting time of 1 action: they're always prepared and you cast them at their lowest level without a slot. After a Long Rest you can swap one."]),
    epicBoon("wizard", B("Dono del richiamo degli incantesimi", "Boon of Spell Recall")),
    f(20, "signature_spells", ["Incantesimi personali", "Signature Spells"], ["Scegli due incantesimi di 3° livello del libro: sono sempre preparati e puoi lanciarli ciascuno una volta al 3° livello senza slot (si ricaricano con un riposo breve o lungo).", "Choose two level 3 spells in your book: they're always prepared and you can cast each once at level 3 without a slot (regained after a Short or Long Rest)."]),
  ],
  subclass: {
    id: "evoker", name: B("Invocatore", "Evoker"), heading: B("Sottoclasse del mago: Invocatore", "Wizard Subclass: Evoker"),
    description: B("Specialista di effetti elementali esplosivi: incantesimi di Invocazione potenziati e controllati.", "A specialist in explosive elemental effects: boosted and controlled Evocation spells."),
    features: [
      f(3, "evocation_savant", ["Invocatore sapiente", "Evocation Savant"], ["Aggiungi gratis al libro due incantesimi da mago di Invocazione di livello 2 o inferiore; a ogni nuovo livello di slot ne aggiungi un altro.", "Add two Wizard Evocation spells of level 2 or lower to your spellbook for free; whenever you gain access to a new slot level you add another."]),
      f(3, "potent_cantrip", ["Trucchetto potente", "Potent Cantrip"], ["Se manchi con un trucchetto o il bersaglio supera il tiro salvezza, subisce comunque metà dei danni (ma nessun effetto aggiuntivo).", "When you miss with a cantrip or the target succeeds on its save, it still takes half the cantrip's damage (but suffers no additional effect)."]),
      f(6, "sculpt_spells", ["Plasmare incantesimi", "Sculpt Spells"], ["Con un incantesimo di Invocazione che colpisce creature visibili ne scegli 1 + il livello dell'incantesimo: superano il tiro salvezza e non subiscono danni nemmeno dimezzati.", "When you cast an Evocation spell affecting creatures you can see, choose 1 + the spell's level of them: they automatically succeed on the save and take no damage even when it would be halved."]),
      f(10, "empowered_evocation", ["Invocazione potente", "Empowered Evocation"], ["Aggiungi Intelligenza a un tiro per i danni di un incantesimo da mago di Invocazione.", "You add your Intelligence modifier to one damage roll of any Wizard Evocation spell."]),
      f(14, "overchannel", ["Saturazione magica", "Overchannel"], ["Con un incantesimo da mago con slot di 1°-5° livello che infligge danni puoi infliggere il massimo dei danni; la prima volta senza effetti avversi, poi 2d12 danni necrotici per livello dell'incantesimo (+1d12 a ogni uso) prima di un riposo lungo.", "When you cast a Wizard spell of level 1-5 that deals damage you can deal maximum damage; the first time with no ill effect, afterward 2d12 Necrotic damage per spell level (+1d12 for each further use) before a Long Rest."]),
    ],
  },
};
