// Druido e Stregone (SRD 5.2.1). Vedi classes-barbarian-fighter.ts per le convenzioni.
import { asi, B, epicBoon, f, opt, slotCols, subclassFeature, type ClassDef } from "./class-types";

const grant = (spell: string, extra: Record<string, unknown> = {}) => ({ op: "grantSpell", spell, mode: "alwaysPrepared", ...extra });
const byLevel = (rows: [number, string[]][], cls: string) => rows.flatMap(([lv, sp]) => sp.map((s) => grant(s, { when: `classLevel:${cls}>=${lv}` })));

export const DRUID: ClassDef = {
  id: "druid", name: B("Druido", "Druid"), hitDie: 8, primary: ["wis"], saves: ["int", "wis"],
  description: B("Custode della natura: Forma selvatica, incantesimi druidici e potere elementale.", "A guardian of nature: Wild Shape, druidic spells, and elemental power."),
  skills: { count: 2, from: ["animal_handling", "arcana", "insight", "medicine", "nature", "perception", "religion", "survival"] },
  armor: ["light", "shield"], weapons: ["simple"], tools: ["herbalism_kit"],
  multiclass: { armor: ["light", "shield"] },
  multiclassPhrases: { it: ["Dado Vita e competenza nelle armature leggere e negli scudi"], en: ["Hit Point Die and training with Light armor and Shields"] },
  caster: { type: "full", ability: "wis", list: "druid" },
  core: { primaryIt: "Saggezza", primaryEn: "Wisdom", savesIt: "Intelligenza e Saggezza", savesEn: "Intelligence and Wisdom", skillsIt: "Due a scelta tra: Addestrare animali, Arcano, Intuizione, Medicina, Natura, Percezione, Religione o Sopravvivenza", skillsEn: "Choose 2: Animal Handling, Arcana, Insight, Medicine, Nature, Perception, Religion, or Survival",
    weaponsIt: "Armi semplici", weaponsEn: "Simple weapons", armorIt: "Armature leggere e scudi", armorEn: "Light armor and Shields", toolsIt: "Borsa da erborista", toolsEn: "Herbalism Kit" },
  equipment: {
    A: { gp: 9, items: [{ item: "leather_armor", it: "un'armatura di cuoio", en: "Leather Armor" }, { item: "shield", it: "uno scudo", en: "Shield" }, { item: "sickle", it: "un falcetto", en: "Sickle" }, { item: "druidic_focus_wooden_staff", it: "focus druidico (bastone ferrato)", en: "Druidic Focus (Quarterstaff)" }, { item: "explorers_pack", it: "una dotazione da esploratore", en: "Explorer's Pack" }, { item: "herbalism_kit", it: "una borsa da erborista", en: "Herbalism Kit" }] },
    B: { gp: 50, items: [] },
  },
  columns: [{ id: "wild_shape", name: B("Forma selvatica", "Wild Shape") }, { id: "cantrips", name: B("Trucchetti", "Cantrips") }, { id: "prepared", name: B("Incantesimi preparati", "Prepared Spells") }, ...slotCols(9)],
  features: [
    f(1, "druidic", ["Druidico", "Druidic"], ["Conosci il Druidico, la lingua segreta dell'ordine (puoi lasciare messaggi nascosti: CD 15 di Intelligenza (Indagare) per notarli). Parlare con gli animali è sempre preparato.", "You know Druidic, the secret language of druids (you can leave hidden messages; DC 15 Intelligence (Investigation) to notice them). Speak with Animals is always prepared."],
      { effects: [grant("speak_with_animals")] }),
    f(1, "spellcasting", ["Incantesimi", "Spellcasting"], ["Lanci incantesimi da druido con Saggezza, usando un focus druidico. Conosci 2 trucchetti (altri al 4° e 10°) e prepari incantesimi (colonna Incantesimi preparati) dalla lista del druido; dopo un riposo lungo puoi cambiare la lista. Gli slot tornano con un riposo lungo.", "You cast Druid spells using Wisdom, with a Druidic Focus. You know 2 cantrips (more at levels 4 and 10) and prepare spells (Prepared Spells column) from the Druid list; after a Long Rest you can change the list. Slots return after a Long Rest."]),
    f(1, "primal_order", ["Ordine primordiale", "Primal Order"], ["Scegli un ruolo sacro: Mago (un trucchetto extra e bonus alle prove di Intelligenza (Arcano o Natura) pari al modificatore di Saggezza, minimo +1) o Custode (competenza con armi da guerra e armature medie).", "Choose a sacred role: Magician (one extra cantrip and a bonus to Intelligence (Arcana or Nature) checks equal to your Wisdom modifier, minimum +1) or Warden (proficiency with Martial weapons and Medium armor)."],
      { choices: [{ id: "druid_primal_order", label: B("Ordine primordiale", "Primal Order"), count: 1, options: [
        { id: "magician", name: B("Mago", "Magician"), effects: [{ op: "extraCantrips", count: 1 }, { op: "checkBonus", value: "max(1, mod:wis)", skills: ["arcana", "nature"] }] },
        { id: "warden", name: B("Custode", "Warden"), effects: [{ op: "grantWeaponProficiency", weapons: ["martial"] }, { op: "grantArmorTraining", training: ["medium"] }] },
      ] }] }),
    f(2, "wild_shape", ["Forma selvatica", "Wild Shape"], ["Come azione bonus assumi la forma di una bestia che conosci (4 forme, GS massimo 1/4 e senza volo; 6 forme e GS 1/2 al 4°; 8 forme, GS 1 e volo all'8°) per ore pari a metà del livello da druido. Ottieni PF temporanei pari al livello da druido; mantieni personalità, PF e privilegi ma non puoi lanciare incantesimi (la concentrazione resta). Usi nella colonna Forma selvatica: 1 con un riposo breve, tutti con uno lungo.", "As a Bonus Action you assume the form of a beast you know (4 forms, max CR 1/4, no Fly Speed; 6 forms and CR 1/2 at level 4; 8 forms, CR 1 and Fly Speed at level 8) for hours equal to half your Druid level. You gain Temporary Hit Points equal to your Druid level; you keep your personality, Hit Points, and features but can't cast spells (Concentration is kept). Uses are in the Wild Shape column: one on a Short Rest, all on a Long Rest."],
      { activation: { resource: "wild_shape", duration: B("metà del livello da druido in ore", "hours equal to half your Druid level") },
        build: (t) => ({ usage: { uses: { table: t.wild_shape }, recharge: "long_rest", partialShortRest: 1 } }) }),
    f(2, "wild_companion", ["Compagno selvatico", "Wild Companion"], ["Come azione di Magia, spendendo uno slot o un uso di Forma selvatica, lanci Trova famiglio senza componenti materiali: il famiglio è un folletto e svanisce dopo un riposo lungo.", "As a Magic action, expending a spell slot or a Wild Shape use, you cast Find Familiar without Material components: the familiar is a Fey and disappears after a Long Rest."]),
    subclassFeature("druid", "del druido", "Druid"),
    asi("druid", 4, false), asi("druid", 8), asi("druid", 12), asi("druid", 16),
    f(5, "wild_resurgence", ["Rinascita selvatica", "Wild Resurgence"], ["Una volta per turno, se hai finito gli usi di Forma selvatica, puoi spendere uno slot per recuperarne uno (senza azione); puoi anche spendere un uso di Forma selvatica per ottenere uno slot di 1° livello, una volta per riposo lungo.", "Once per turn, if you have no Wild Shape uses left, you can expend a spell slot to regain one (no action); you can also expend a Wild Shape use to gain a level 1 slot, once per Long Rest."]),
    f(7, "elemental_fury", ["Furia elementale", "Elemental Fury"], ["Scegli: Incantesimi potenti (aggiungi Saggezza ai danni dei trucchetti da druido) o Colpo primordiale (una volta per turno, quando colpisci con un'arma o un attacco in Forma selvatica, +1d8 danni da freddo, fuoco, fulmine o tuono).", "Choose: Potent Spellcasting (add Wisdom to Druid cantrip damage) or Primal Strike (once per turn, when you hit with a weapon or a Wild Shape attack, +1d8 Cold, Fire, Lightning, or Thunder damage)."],
      { choices: [{ id: "druid_elemental_fury", label: B("Furia elementale", "Elemental Fury"), count: 1, options: [{ id: "potent_spellcasting", name: B("Incantesimi potenti", "Potent Spellcasting") }, { id: "primal_strike", name: B("Colpo primordiale", "Primal Strike") }] }] }),
    f(15, "improved_elemental_fury", ["Furia elementale migliorata", "Improved Elemental Fury"], ["Incantesimi potenti: i trucchetti da druido con gittata di 3 m o più hanno gittata +90 m. Colpo primordiale: danni extra 2d8.", "Potent Spellcasting: Druid cantrips with a range of 10 feet or more gain +300 feet of range. Primal Strike: extra damage becomes 2d8."]),
    f(18, "beast_spells", ["Incantesimi bestiali", "Beast Spells"], ["In Forma selvatica puoi lanciare incantesimi, tranne quelli con componenti materiali costose o consumate.", "While in Wild Shape you can cast spells, except those with costly or consumed Material components."]),
    epicBoon("druid", B("Dono del viaggio dimensionale", "Boon of Dimensional Travel")),
    f(20, "archdruid", ["Arcidruido", "Archdruid"], ["Forma selvatica sempreverde (tirando l'iniziativa senza usi ne recuperi uno); Mago della natura (converti usi di Forma selvatica in uno slot, 2 livelli per uso, una volta per riposo lungo); Corpo senza tempo (invecchi di 1 anno ogni 10).", "Evergreen Wild Shape (when you roll Initiative with no uses you regain one); Nature Magician (convert Wild Shape uses into one spell slot, 2 spell levels per use, once per Long Rest); Timeless Body (you age 1 year for every 10)."]),
  ],
  subclass: {
    id: "land", name: B("Circolo della Terra", "Circle of the Land"), heading: B("Sottoclasse del druido: Circolo della Terra", "Druid Subclass: Circle of the Land"),
    description: B("Mistico legato a un tipo di terra: incantesimi del circolo, Ausilio dalla terra e protezione dalla natura.", "A mystic tied to a land type: circle spells, Land's Aid, and nature's protection."),
    checkPhrases: { it: ["Dardo di fuoco , mani brucianti , sfocatura", "Blocca persone , nube di nebbia , raggio di gelo", "Passo velato , sonno e stretta folgorante", "Fiotto acido , raggio di infermità , ragnatela"], en: ["Blur, Burning Hands, Fire Bolt", "Fog Cloud, Hold Person, Ray of Frost", "Misty Step, Shocking Grasp, Sleep", "Acid Splash, Ray of Sickness, Web"] },
    features: [
      f(3, "circle_of_the_land_spells", ["Incantesimi del Circolo della Terra", "Circle of the Land Spells"], ["Dopo un riposo lungo scegli un tipo di terra (arida, polare, temperata, tropicale): gli incantesimi elencati per il tuo livello e i livelli inferiori sono preparati. Arida: 3° Dardo di fuoco, Mani brucianti, Sfocatura; 5° Palla di fuoco; 7° Inaridire; 9° Muro di pietra. Polare: 3° Blocca persone, Nube di nebbia, Raggio di gelo; 5° Tempesta di nevischio; 7° Tempesta di ghiaccio; 9° Cono di freddo. Temperata: 3° Passo velato, Sonno, Stretta folgorante; 5° Fulmine; 7° Libertà di movimento; 9° Traslazione arborea. Tropicale: 3° Fiotto acido, Raggio di infermità, Ragnatela; 5° Nube maleodorante; 7° Metamorfosi; 9° Piaga degli insetti.", "After a Long Rest choose a land type (arid, polar, temperate, tropical): the spells listed for your level and lower are prepared. Arid: 3 Blur, Burning Hands, Fire Bolt; 5 Fireball; 7 Blight; 9 Wall of Stone. Polar: 3 Fog Cloud, Hold Person, Ray of Frost; 5 Sleet Storm; 7 Ice Storm; 9 Cone of Cold. Temperate: 3 Misty Step, Shocking Grasp, Sleep; 5 Lightning Bolt; 7 Freedom of Movement; 9 Tree Stride. Tropical: 3 Acid Splash, Ray of Sickness, Web; 5 Stinking Cloud; 7 Polymorph; 9 Insect Plague."],
        { choices: [{ id: "land_type", label: B("Tipo di terra", "Land type"), count: 1, options: [
          { id: "arid", name: B("Terra arida", "Arid Land"), effects: [...byLevel([[3, ["fire_bolt", "burning_hands", "blur"]], [5, ["fireball"]], [7, ["blight"]], [9, ["wall_of_stone"]]], "druid"), { op: "resistance", types: ["fire"], when: "classLevel:druid>=10" }] },
          { id: "polar", name: B("Terra polare", "Polar Land"), effects: [...byLevel([[3, ["hold_person", "fog_cloud", "ray_of_frost"]], [5, ["sleet_storm"]], [7, ["ice_storm"]], [9, ["cone_of_cold"]]], "druid"), { op: "resistance", types: ["cold"], when: "classLevel:druid>=10" }] },
          { id: "temperate", name: B("Terra temperata", "Temperate Land"), effects: [...byLevel([[3, ["misty_step", "sleep", "shocking_grasp"]], [5, ["lightning_bolt"]], [7, ["freedom_of_movement"]], [9, ["tree_stride"]]], "druid"), { op: "resistance", types: ["lightning"], when: "classLevel:druid>=10" }] },
          { id: "tropical", name: B("Terra tropicale", "Tropical Land"), effects: [...byLevel([[3, ["acid_splash", "ray_of_sickness", "web"]], [5, ["stinking_cloud"]], [7, ["polymorph"]], [9, ["insect_plague"]]], "druid"), { op: "resistance", types: ["poison"], when: "classLevel:druid>=10" }] },
        ] }] }),
      f(3, "lands_aid", ["Ausilio dalla terra", "Land's Aid"], ["Azione di Magia, spendendo un uso di Forma selvatica: scegli un punto entro 18 m; in una sfera di 3 m le creature a tua scelta fanno un tiro salvezza su Costituzione o subiscono 2d6 danni necrotici (metà se superato), e una creatura a tua scelta recupera 2d6 PF. 3d6 al 10° livello, 4d6 al 14°.", "Magic action, expending a Wild Shape use: choose a point within 60 feet; in a 10-foot-radius Sphere creatures of your choice make a Constitution save or take 2d6 Necrotic damage (half on a success), and one creature of your choice regains 2d6 Hit Points. 3d6 at level 10, 4d6 at level 14."]),
      f(6, "natural_recovery", ["Recupero naturale", "Natural Recovery"], ["Puoi lanciare senza slot uno degli incantesimi del Circolo che hai preparato (una volta per riposo lungo); dopo un riposo breve recuperi slot di livello totale pari a metà del livello da druido (per eccesso), nessuno oltre il 6°, una volta per riposo lungo.", "You can cast one of your Circle spells without a slot (once per Long Rest); after a Short Rest you recover slots with a combined level up to half your Druid level (rounded up), none above level 6, once per Long Rest."], { usage: { uses: 1, recharge: "long_rest" } }),
      f(10, "natures_ward", ["Interdizione della Natura", "Nature's Ward"], ["Sei immune alla condizione avvelenato e hai resistenza a un tipo di danno legato alla terra scelta (arida: fuoco; polare: freddo; temperata: fulmine; tropicale: veleno).", "You have Immunity to the Poisoned condition and Resistance to a damage type tied to your chosen land (arid: Fire; polar: Cold; temperate: Lightning; tropical: Poison)."]),
      f(14, "natures_sanctuary", ["Rifugio della Natura", "Nature's Sanctuary"], ["Azione di Magia, spendendo un uso di Forma selvatica: alberi e viticci spettrali in un cubo di 4,5 m entro 36 m per 1 minuto; tu e i tuoi alleati avete mezza copertura e gli alleati ottengono la resistenza di Interdizione della Natura. Azione bonus: sposta il cubo fino a 18 m.", "Magic action, expending a Wild Shape use: spectral trees and vines fill a 15-foot Cube within 120 feet for 1 minute; you and your allies have Half Cover and allies gain the Resistance from Nature's Ward. Bonus Action: move the Cube up to 60 feet."]),
    ],
  },
};

const META = (id: string, it: string, en: string, cost: number, dIt: string, dEn: string) => opt(id, [it, en], [dIt, dEn], { cost });
const METAMAGIC = [
  META("subtle_spell", "Incantesimo celato", "Subtle Spell", 1, "Lanci un incantesimo senza componenti verbali, somatiche o materiali (tranne quelle consumate o con costo).", "Cast a spell without Verbal, Somatic, or Material components (except consumed or costed ones)."),
  META("distant_spell", "Incantesimo distante", "Distant Spell", 1, "Raddoppia la gittata di un incantesimo di 1,5 m o più; un incantesimo a contatto passa a 9 m.", "Double the range of a spell with a range of 5 feet or more; a Touch spell becomes 30 feet."),
  META("extended_spell", "Incantesimo esteso", "Extended Spell", 1, "Raddoppia la durata di un incantesimo di 1 minuto o più (max 24 ore); Vantaggio ai tiri per mantenere la concentrazione.", "Double the duration of a spell of 1 minute or more (max 24 hours); Advantage on saves to keep Concentration."),
  META("heightened_spell", "Incantesimo intensificato", "Heightened Spell", 2, "Un bersaglio ha Svantaggio ai tiri salvezza contro l'incantesimo.", "One target has Disadvantage on saving throws against the spell."),
  META("seeking_spell", "Incantesimo mirato", "Seeking Spell", 1, "Se manchi con il tiro per colpire di un incantesimo, ritiri il d20 (usi il nuovo risultato); si può combinare con un'altra opzione.", "If you miss with a spell attack roll, reroll the d20 (use the new roll); can be combined with another option."),
  META("empowered_spell", "Incantesimo potenziato", "Empowered Spell", 1, "Ritiri fino a Carisma dadi di danno di un incantesimo (minimo 1); si può combinare con un'altra opzione.", "Reroll up to your Charisma modifier damage dice of a spell (minimum 1); can be combined with another option."),
  META("careful_spell", "Incantesimo preciso", "Careful Spell", 1, "Proteggi fino a Carisma creature (minimo 1): superano automaticamente il tiro salvezza e non subiscono danni neanche dimezzati.", "Protect up to your Charisma modifier creatures (minimum 1): they automatically succeed on the save and take no damage even when it would be halved."),
  META("twinned_spell", "Incantesimo raddoppiato", "Twinned Spell", 1, "Per un incantesimo che si potenzia con slot più alti per colpire un bersaglio in più, il livello effettivo aumenta di 1.", "For a spell that targets one more creature at a higher slot level, treat its level as 1 higher."),
  META("quickened_spell", "Incantesimo rapido", "Quickened Spell", 2, "Un incantesimo di 1 azione si lancia con 1 azione bonus (se non hai già lanciato un incantesimo di 1° livello o superiore nel turno).", "A spell with a casting time of 1 action is cast as a Bonus Action (if you haven't cast a level 1+ spell this turn)."),
  META("transmuted_spell", "Incantesimo trasmutato", "Transmuted Spell", 1, "Cambi il tipo di danno di un incantesimo tra acido, freddo, fulmine, fuoco, tuono e veleno.", "Change a spell's damage type among Acid, Cold, Lightning, Fire, Thunder, and Poison."),
];
const metamagicChoice = (level: number, count: number) => ({ id: `sorcerer_metamagic_${level}`, label: B("Metamagia", "Metamagic"), count, options: METAMAGIC });

export const SORCERER: ClassDef = {
  id: "sorcerer", name: B("Stregone", "Sorcerer"), hitDie: 6, primary: ["cha"], saves: ["con", "cha"],
  description: B("Incantatore dalla magia innata: punti stregoneria, Metamagia e Stregoneria innata.", "A caster with innate magic: Sorcery Points, Metamagic, and Innate Sorcery."),
  skills: { count: 2, from: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"] },
  armor: [], weapons: ["simple"], multiclass: {},
  multiclassPhrases: { it: ["Ottiene il Dado Vita dalla tabella Tratti dello stregone"], en: ["Gain the Hit Point Die from the Core Sorcerer Traits table"] },
  caster: { type: "full", ability: "cha", list: "sorcerer" },
  checkPhrases: { it: METAMAGIC.map((o) => (o.name as { it: string }).it), en: METAMAGIC.map((o) => (o.name as { en: string }).en) },
  core: { primaryIt: "Carisma", primaryEn: "Charisma", savesIt: "Costituzione e Carisma", savesEn: "Constitution and Charisma", skillsIt: "Due a scelta tra: Arcano, Inganno, Intimidire, Intuizione, Persuasione o Religione", skillsEn: "Choose 2: Arcana, Deception, Insight, Intimidation, Persuasion, or Religion",
    weaponsIt: "Armi semplici", weaponsEn: "Simple weapons", armorIt: "Nessuno", armorEn: "None" },
  equipment: {
    A: { gp: 28, items: [{ item: "spear", it: "lancia", en: "Spear" }, { item: "dagger", qty: 2, it: "2 pugnali", en: "2 Daggers" }, { item: "arcane_focus_crystal", it: "focus arcano (cristallo)", en: "Arcane Focus (crystal)" }, { item: "dungeoneers_pack", it: "dotazione da avventuriero", en: "Dungeoneer's Pack" }] },
    B: { gp: 50, items: [] },
  },
  columns: [{ id: "sorcery_points", name: B("Punti stregoneria", "Sorcery Points") }, { id: "cantrips", name: B("Trucchetti", "Cantrips") }, { id: "prepared", name: B("Incantesimi preparati", "Prepared Spells") }, ...slotCols(9)],
  features: [
    f(1, "spellcasting", ["Incantesimi", "Spellcasting"], ["Lanci incantesimi da stregone con Carisma, usando un focus arcano. Conosci 4 trucchetti (altri al 4° e 10°) e prepari incantesimi (colonna Incantesimi preparati) dalla lista dello stregone; dopo un riposo lungo puoi sostituirne uno. Gli slot tornano con un riposo lungo.", "You cast Sorcerer spells using Charisma, with an Arcane Focus. You know 4 cantrips (more at levels 4 and 10) and prepare spells (Prepared Spells column) from the Sorcerer list; after a Long Rest you can swap one. Slots return after a Long Rest."]),
    f(1, "innate_sorcery", ["Stregoneria innata", "Innate Sorcery"], ["Come azione bonus per 1 minuto: la CD degli incantesimi da stregone sale di 1 e hai Vantaggio ai tiri per colpire degli incantesimi. Due usi, tornano con un riposo lungo.", "As a Bonus Action for 1 minute: your Sorcerer spell save DC increases by 1 and you have Advantage on spell attack rolls. Two uses, regained on a Long Rest."],
      { usage: { uses: 2, recharge: "long_rest" }, activation: { resource: "innate_sorcery", duration: B("1 minuto", "1 minute") } }),
    f(2, "font_of_magic", ["Fonte di magia", "Font of Magic"], ["Hai punti stregoneria (colonna Punti stregoneria; tornano con un riposo lungo). Puoi convertire slot in punti (punti = livello dello slot, senza azione) e creare slot con un'azione bonus (costo: 1° 2 punti, 2° 3, 3° 5, 4° 6, 5° 7; livello da stregone minimo 2, 3, 5, 7, 9; gli slot creati svaniscono con un riposo lungo).", "You have Sorcery Points (Sorcery Points column; regained on a Long Rest). You can convert slots into points (points = slot level, no action) and create slots as a Bonus Action (cost: level 1 2 points, level 2 3, level 3 5, level 4 6, level 5 7; minimum Sorcerer level 2, 3, 5, 7, 9; created slots vanish after a Long Rest)."],
      { build: (t) => ({ usage: { uses: { table: t.sorcery_points }, recharge: "long_rest" } }) }),
    f(2, "metamagic", ["Metamagia", "Metamagic"], ["Ottieni due opzioni di Metamagia (altre due al 10° e al 17° livello): le usi spendendo punti stregoneria, una per incantesimo (salvo diversa indicazione). A ogni livello da stregone puoi sostituirne una.", "You gain two Metamagic options (two more at levels 10 and 17): you use them by spending Sorcery Points, one per spell (unless noted). Whenever you gain a Sorcerer level you can replace one."],
      { choices: [metamagicChoice(2, 2)] }),
    subclassFeature("sorcerer", "dello stregone", "Sorcerer"),
    asi("sorcerer", 4, false), asi("sorcerer", 8), asi("sorcerer", 12), asi("sorcerer", 16),
    f(5, "sorcerous_restoration", ["Ripristino stregonesco", "Sorcerous Restoration"], ["Con un riposo breve recuperi punti stregoneria fino a metà del tuo livello da stregone (per difetto). Una volta per riposo lungo.", "After a Short Rest you regain Sorcery Points up to half your Sorcerer level (rounded down). Once per Long Rest."], { usage: { uses: 1, recharge: "long_rest" } }),
    f(7, "sorcery_incarnate", ["Stregoneria incarnata", "Sorcery Incarnate"], ["Se hai finito gli usi di Stregoneria innata puoi attivarla spendendo 2 punti stregoneria (azione bonus); mentre è attiva puoi usare fino a due opzioni di Metamagia per incantesimo.", "If you have no Innate Sorcery uses left you can activate it by spending 2 Sorcery Points (Bonus Action); while it's active you can use up to two Metamagic options per spell."]),
    f(10, "metamagic_10", ["Metamagia", "Metamagic"], ["Altre due opzioni di Metamagia.", "Two more Metamagic options."], { tableOnly: true, choices: [metamagicChoice(10, 2)] }),
    f(17, "metamagic_17", ["Metamagia", "Metamagic"], ["Altre due opzioni di Metamagia.", "Two more Metamagic options."], { tableOnly: true, choices: [metamagicChoice(17, 2)] }),
    epicBoon("sorcerer", B("Dono del viaggio dimensionale", "Boon of Dimensional Travel")),
    f(20, "arcane_apotheosis", ["Apoteosi arcana", "Arcane Apotheosis"], ["Con Stregoneria innata attiva puoi usare un'opzione di Metamagia per turno senza spendere punti stregoneria.", "While Innate Sorcery is active you can use one Metamagic option per turn without spending Sorcery Points."]),
  ],
  subclass: {
    id: "draconic", name: B("Stregoneria draconica", "Draconic Sorcery"), heading: B("Sottoclasse dello stregone: Stregoneria draconica", "Sorcerer Subclass: Draconic Sorcery"),
    description: B("Magia innata del drago: resilienza, incantesimi draconici, affinità elementale, ali e un drago alleato.", "Innate dragon magic: resilience, draconic spells, elemental affinity, wings, and a dragon ally."),
    checkPhrases: { it: ["Alterare se stesso , globo cromatico , comando , soffio del drago", "Paura , volare", "Occhio arcano , charme sui mostri", "Conoscenza delle leggende , richiama drago"], en: ["Alter Self, Chromatic Orb, Command, Dragon's Breath", "Fear, Fly", "Arcane Eye, Charm Monster", "Legend Lore, Summon Dragon"] },
    features: [
      f(3, "draconic_resilience", ["Resilienza draconica", "Draconic Resilience"], ["I PF massimi aumentano di 3 e di 1 per ogni livello da stregone. Senza armatura la CA base è 10 + Des + Car.", "Your Hit Point maximum increases by 3, and by 1 again whenever you gain a Sorcerer level. While not wearing armor your base AC is 10 + Dex + Cha."],
        { effects: [{ op: "hpMaxBonus", value: 3 }, { op: "hpMaxPerLevel", value: 1, classId: "sorcerer" }, { op: "acFormula", formula: "10 + mod:dex + mod:cha", shieldAllowed: true, when: "wearingArmor:none" }] }),
      f(3, "draconic_spells", ["Incantesimi draconici", "Draconic Spells"], ["Incantesimi sempre preparati: 3° Alterare se stesso, Globo cromatico, Comando, Soffio del drago; 5° Paura, Volare; 7° Occhio arcano, Charme sui mostri; 9° Conoscenza delle leggende, Richiama drago.", "Always-prepared spells: level 3 Alter Self, Chromatic Orb, Command, Dragon's Breath; 5 Fear, Fly; 7 Arcane Eye, Charm Monster; 9 Legend Lore, Summon Dragon."],
        { effects: byLevel([[3, ["alter_self", "chromatic_orb", "command", "dragons_breath"]], [5, ["fear", "fly"]], [7, ["arcane_eye", "charm_monster"]], [9, ["legend_lore", "summon_dragon"]]], "sorcerer") }),
      f(6, "elemental_affinity", ["Affinità elementale", "Elemental Affinity"], ["Scegli un tipo di danno draconico (acido, freddo, fulmine, fuoco o veleno): hai resistenza e, quando lanci un incantesimo di quel tipo, aggiungi Carisma a un tiro per i danni.", "Choose a draconic damage type (Acid, Cold, Lightning, Fire, or Poison): you gain Resistance to it and, when you cast a spell of that type, add your Charisma modifier to one damage roll."],
        { choices: [{ id: "sorcerer_elemental_affinity", label: B("Affinità elementale", "Elemental Affinity"), count: 1, options: ["acid", "cold", "lightning", "fire", "poison"].map((d) => ({ id: d, name: { it: `$damage:${d}`, en: `$damage:${d}` }, effects: [{ op: "resistance", types: [d] }] })) }] }),
      f(14, "dragon_wings", ["Ali di drago", "Dragon Wings"], ["Azione bonus: ali draconiche per 1 ora (o finché le fai sparire) con velocità di volo di 18 m. Una volta per riposo lungo, o spendendo 3 punti stregoneria.", "Bonus Action: dragon wings for 1 hour (or until dismissed) with a Fly Speed of 60 feet. Once per Long Rest, or by spending 3 Sorcery Points."], { usage: { uses: 1, recharge: "long_rest" } }),
      f(18, "dragon_companion", ["Seguace draconico", "Dragon Companion"], ["Puoi lanciare Richiama drago senza componenti materiali e una volta senza slot per riposo lungo; puoi lanciarlo senza concentrazione (durata 1 minuto).", "You can cast Summon Dragon without Material components and once without a slot per Long Rest; you can cast it without Concentration (duration 1 minute)."], { effects: [grant("summon_dragon", { freeCast: { uses: 1, recharge: "long_rest" } })] }),
    ],
  },
};
