// Descrizioni brevi delle voci dello step 2a, riscritte con parole nostre (non copiate dal PDF) a partire dall'SRD 5.2.1.
// Il testo dei PDF fa fede per le regole: queste sono sintesi per l'interfaccia. Chiave = id della voce.
export type Desc = { it: string; en: string };
export const DESCRIPTIONS: Record<string, Record<string, Desc>> = {
  items: {
    acid: { it: "Al posto di un attacco lanci una fiala su una creatura o un oggetto entro 6 m: TS su Destrezza (CD 8 + Destrezza + competenza) o subisce danni da acido.", en: "Instead of one attack, throw a vial at a creature or object within 20 ft: Dexterity save (DC 8 + Dex + proficiency) or take Acid damage." },
    alchemists_fire: { it: "Al posto di un attacco lanci una ampolla entro 6 m: TS su Destrezza (CD 8 + Destrezza + competenza) o subisce 1d4 danni da fuoco e prende fuoco.", en: "Instead of one attack, throw a flask within 20 ft: Dexterity save (DC 8 + Dex + proficiency) or take 1d4 Fire damage and start burning." },
    antitoxin: { it: "Come azione bonus la bevi per avere vantaggio ai tiri salvezza per evitare o interrompere la condizione Avvelenato.", en: "As a Bonus Action, drink it to gain Advantage on saving throws to avoid or end the Poisoned condition." },
    ball_bearings: { it: "Con l'azione Utilizzo li spargi su 3 m² entro 3 m: chi entra deve superare un TS su Destrezza CD 10 o cade Prono.", en: "Use action to spill them over a 10-ft square within 10 ft: a creature must pass a DC 10 Dexterity save or fall Prone." },
    bell: { it: "Suonata con l'azione Utilizzo, si sente fino a 18 m di distanza.", en: "Rung with the Utilize action, it can be heard up to 60 ft away." },
    block_and_tackle: { it: "Permette di sollevare fino a quattro volte il peso che solleveresti normalmente.", en: "Lets you lift up to four times the weight you normally could." },
    caltrops: { it: "Con l'azione Utilizzo li spargi su 1,5 m² entro 1,5 m: chi entra per la prima volta in un turno supera un TS su Destrezza CD 15 o subisce 1 danno perforante e ha velocità 0 fino al suo prossimo turno.", en: "Use action to scatter them over a 5-ft square within 5 ft: a creature entering for the first time on a turn must pass a DC 15 Dexterity save or take 1 Piercing damage and have Speed 0 until its next turn." },
    climbers_kit: { it: "Con l'azione Utilizzo fissi un'ancora: non puoi cadere né allontanarti di oltre 7,5 m dal punto di ancoraggio finché non la sganci (azione bonus).", en: "Use action to set an anchor: you can't fall or move more than 25 ft from the anchor point until you undo it (Bonus Action)." },
    component_pouch: { it: "Impermeabile, contiene tutte le componenti materiali sfuse dei tuoi incantesimi (quelle senza costo).", en: "Waterproof, it holds all the loose material components for your spells (those without a cost)." },
    healers_kit: { it: "Ha dieci usi. Con l'azione Utilizzo ne spendi uno per stabilizzare una creatura priva di sensi a 0 punti ferita, senza prova di Saggezza (Medicina).", en: "Has ten uses. As a Utilize action, spend one to stabilize an Unconscious creature at 0 Hit Points without a Wisdom (Medicine) check." },
    holy_water: { it: "Al posto di un attacco la lanci entro 6 m: TS su Destrezza (CD 8 + Destrezza + competenza) o subisce danni radiosi, se è un Immondo o un Non morto.", en: "Instead of one attack, throw it within 20 ft: Dexterity save (DC 8 + Dex + proficiency) or take Radiant damage if it is a Fiend or an Undead." },
    hunting_trap: { it: "La piazzi con l'azione Utilizzo: chi ci entra supera un TS su Destrezza CD 13 o subisce 1d4 danni perforanti e ha velocità 0 finché non si libera.", en: "Set it with the Utilize action: a creature entering must pass a DC 13 Dexterity save or take 1d4 Piercing damage and have Speed 0 until freed." },
    ladder: { it: "Alta 3 m.", en: "10 feet tall." },
    lamp: { it: "Brucia olio: luce intensa entro 4,5 m e fioca per altri 9 m.", en: "Burns oil: Bright Light in a 15-ft radius and Dim Light for another 30 ft." },
    bullseye_lantern: { it: "Brucia olio: luce intensa in un cono di 18 m e fioca per altri 18 m.", en: "Burns oil: Bright Light in a 60-ft Cone and Dim Light for another 60 ft." },
    hooded_lantern: { it: "Brucia olio: luce intensa entro 9 m e fioca per altri 9 m; con l'azione bonus si abbassa lo schermo e resta luce fioca.", en: "Burns oil: Bright Light in a 30-ft radius and Dim Light for another 30 ft; as a Bonus Action you can lower the hood for Dim Light only." },
    lock: { it: "Si apre con le chiavi o con una prova di Destrezza (Rapidità di mano) CD 15.", en: "Opens with its key or a DC 15 Dexterity (Sleight of Hand) check." },
    manacles: { it: "Con l'azione Utilizzo (prova di Destrezza, Rapidità di mano, CD 13) blocchi una creatura Piccola o Media afferrata, incapacitata o trattenuta entro 1,5 m.", en: "Use action (DC 13 Dexterity (Sleight of Hand) check) to bind a Small or Medium creature within 5 ft that is Grappled, Incapacitated, or Restrained." },
    net: { it: "La lanci entro 4,5 m: se il bersaglio fallisce il TS su Destrezza è Trattenuto; si libera con una prova di Forza CD 10 o distruggendo la rete.", en: "Throw it within 15 ft: a target that fails the Dexterity save is Restrained; it escapes with a DC 10 Strength check or by destroying the net." },
    oil: { it: "Lanciata addosso a un bersaglio lo copre: subisce danni extra da fuoco se colpito dal fuoco. Versata su 1,5 m² e incendiata brucia per 2 round infliggendo 5 danni da fuoco a chi entra o finisce il turno lì.", en: "Thrown at a target it coats it: extra Fire damage if it takes Fire damage. Poured over a 5-ft square and lit, it burns for 2 rounds, dealing 5 Fire damage to creatures entering or ending their turn there." },
    basic_poison: { it: "Come azione bonus ne spalmi una fiala su un'arma o munizione: il prossimo colpo infligge 1d4 danni da veleno in più.", en: "As a Bonus Action, coat a weapon or ammunition: its next hit deals an extra 1d4 Poison damage." },
    pole: { it: "Lunga 3 m.", en: "10 feet long." },
    portable_ram: { it: "Serve a sfondare le porte: dà un bonus di +4 alla prova di Forza.", en: "Used to break down doors: gives a +4 bonus to the Strength check." },
    potion_of_healing: { it: "Oggetto magico. Come azione bonus la bevi (o la dai a una creatura entro 1,5 m) e recuperi 2d4 + 2 punti ferita.", en: "Magic item. As a Bonus Action, drink it (or give it to a creature within 5 ft) to regain 2d4 + 2 Hit Points." },
    rope: { it: "Con l'azione Utilizzo fai un nodo (prova di Destrezza, Rapidità di mano, CD 10); si spezza con una prova di Forza (Atletica) CD 20.", en: "Use action to tie a knot (DC 10 Dexterity (Sleight of Hand) check); it can be burst with a DC 20 Strength (Athletics) check." },
    spyglass: { it: "Gli oggetti osservati appaiono grandi il doppio.", en: "Objects viewed through it appear twice as large." },
    tent: { it: "Ci dormono al massimo due creature Piccole o Medie.", en: "Sleeps up to two Small or Medium creatures." },
    torch: { it: "Arde per 1 ora: luce intensa entro 6 m e fioca per altri 6 m. Usata come arma da mischia semplice infligge 1 danno da fuoco.", en: "Burns for 1 hour: Bright Light in a 20-ft radius and Dim Light for another 20 ft. Used as a simple melee weapon it deals 1 Fire damage." },
  },
  skills: {
    acrobatics: { it: "Restare in piedi in una situazione difficile o eseguire un'acrobazia.", en: "Keep your footing in a tricky spot or pull off an acrobatic stunt." },
    animal_handling: { it: "Calmare o addestrare un animale, o ottenere che si comporti in un certo modo.", en: "Calm or train an animal, or get it to behave a certain way." },
    arcana: { it: "Ricordare nozioni su incantesimi, oggetti magici e piani di esistenza.", en: "Recall lore about spells, magic items, and the planes of existence." },
    athletics: { it: "Saltare più lontano del normale, restare a galla in acque agitate o rompere qualcosa.", en: "Jump farther than usual, stay afloat in rough water, or break something." },
    deception: { it: "Dire una bugia convincente o travestirsi in modo credibile.", en: "Tell a convincing lie or wear a believable disguise." },
    history: { it: "Ricordare nozioni su eventi storici, personaggi, nazioni e culture.", en: "Recall lore about historical events, people, nations, and cultures." },
    insight: { it: "Capire l'umore e le intenzioni di una persona.", en: "Read a person's mood and intentions." },
    intimidation: { it: "Ottenere ciò che vuoi incutendo timore o minacciando.", en: "Get what you want by awing or threatening someone." },
    investigation: { it: "Trovare informazioni nascoste nei libri o dedurre come funziona qualcosa.", en: "Dig up obscure information in books or work out how something functions." },
    medicine: { it: "Diagnosticare una malattia o stabilire cosa ha ucciso una creatura morta da poco.", en: "Diagnose an illness or work out what killed someone recently dead." },
    nature: { it: "Ricordare nozioni su terreni, piante, animali e clima.", en: "Recall lore about terrain, plants, animals, and weather." },
    perception: { it: "Accorgersi di qualcosa che sfugge facilmente, usando insieme i sensi.", en: "Notice something easy to miss by using your senses together." },
    performance: { it: "Recitare, raccontare una storia, suonare o ballare.", en: "Act, tell a story, play music, or dance." },
    persuasion: { it: "Convincere qualcuno di qualcosa in modo onesto e cortese.", en: "Convince someone of something honestly and graciously." },
    religion: { it: "Ricordare nozioni su divinità, riti religiosi e simboli sacri.", en: "Recall lore about gods, religious rites, and holy symbols." },
    sleight_of_hand: { it: "Borseggiare, nascondere un oggetto che si tiene in mano o fare giochi di prestigio.", en: "Pick a pocket, hide a handheld object, or perform sleight of hand." },
    stealth: { it: "Passare inosservato muovendosi in silenzio e nascondendosi dietro qualcosa.", en: "Avoid notice by moving quietly and hiding behind things." },
    survival: { it: "Seguire tracce, cercare cibo, trovare un sentiero o evitare i pericoli naturali.", en: "Follow tracks, forage, find a trail, or avoid natural hazards." },
  },
  sizes: {
    tiny: { it: "Occupa uno spazio di 2,5 × 2,5 piedi: ne entrano 4 in una casella.", en: "Occupies a 2½ × 2½ ft space: four fit in one square." },
    small: { it: "Occupa una casella di 5 × 5 piedi.", en: "Occupies one 5 × 5 ft square." },
    medium: { it: "Occupa una casella di 5 × 5 piedi.", en: "Occupies one 5 × 5 ft square." },
    large: { it: "Occupa uno spazio di 10 × 10 piedi (2 × 2 caselle).", en: "Occupies a 10 × 10 ft space (2 × 2 squares)." },
    huge: { it: "Occupa uno spazio di 15 × 15 piedi (3 × 3 caselle).", en: "Occupies a 15 × 15 ft space (3 × 3 squares)." },
    gargantuan: { it: "Occupa uno spazio di 20 × 20 piedi (4 × 4 caselle).", en: "Occupies a 20 × 20 ft space (4 × 4 squares)." },
  },
  damageTypes: {
    acid: { it: "Liquidi corrosivi, enzimi digestivi.", en: "Corrosive liquids, digestive enzymes." },
    bludgeoning: { it: "Oggetti contundenti, costrizione, cadute.", en: "Blunt objects, constriction, falling." },
    cold: { it: "Acqua gelida, soffi di ghiaccio.", en: "Freezing water, icy blasts." },
    fire: { it: "Fiamme, calore insopportabile.", en: "Flames, unbearable heat." },
    force: { it: "Pura energia magica.", en: "Pure magical energy." },
    lightning: { it: "Elettricità.", en: "Electricity." },
    necrotic: { it: "Energia che prosciuga la vita.", en: "Life-draining energy." },
    piercing: { it: "Zanne, oggetti che perforano.", en: "Fangs, puncturing objects." },
    poison: { it: "Gas tossici, veleni.", en: "Toxic gas, venom." },
    psychic: { it: "Energia che dilania la mente.", en: "Mind-rending energy." },
    radiant: { it: "Energia sacra, radiazioni ustionanti.", en: "Holy energy, searing radiation." },
    slashing: { it: "Artigli, oggetti taglienti.", en: "Claws, cutting objects." },
    thunder: { it: "Suono dirompente.", en: "Concussive sound." },
  },
  weaponProperties: {
    ammunition: { it: "Serve munizionamento per attaccare a distanza: ogni attacco ne consuma una. Estrarla fa parte dell'attacco (serve una mano libera per caricare un'arma a una mano). Dopo il combattimento, con 1 minuto recuperi metà delle munizioni usate (per difetto).", en: "You need ammunition to make a ranged attack, and each attack uses one piece. Drawing it is part of the attack (you need a free hand to load a one-handed weapon). After a fight, 1 minute recovers half the ammunition you used, rounded down." },
    finesse: { it: "Per tiro per colpire e danni puoi usare il modificatore di Forza o di Destrezza, a scelta, ma lo stesso per entrambi.", en: "Use your choice of Strength or Dexterity for the attack and damage rolls, but the same one for both." },
    heavy: { it: "Hai Svantaggio ai tiri per colpire se l'arma è da mischia e hai Forza inferiore a 13, o a distanza e hai Destrezza inferiore a 13.", en: "You have Disadvantage on attack rolls if the weapon is Melee and your Strength is below 13, or Ranged and your Dexterity is below 13." },
    light: { it: "Se con l'azione Attacco colpisci con un'arma Leggera, puoi fare un attacco extra come azione bonus nello stesso turno, con un'altra arma Leggera. Al danno dell'attacco extra non aggiungi il modificatore (salvo che sia negativo).", en: "When you take the Attack action with a Light weapon, you can make one extra attack as a Bonus Action that turn with a different Light weapon. You don't add your ability modifier to that extra attack's damage unless it's negative." },
    loading: { it: "Con un'azione, azione bonus o reazione puoi sparare un solo proiettile, a prescindere da quanti attacchi avresti.", en: "You can fire only one piece of ammunition per action, Bonus Action, or Reaction, however many attacks you normally have." },
    range: { it: "Due numeri tra parentesi: gittata normale e gittata lunga, in piedi. Oltre la normale hai Svantaggio; oltre la lunga non puoi attaccare.", en: "Two numbers in parentheses: normal range and long range, in feet. Beyond normal range you have Disadvantage; beyond long range you can't attack." },
    reach: { it: "Aggiunge 5 piedi alla tua portata quando attacchi con l'arma e per gli attacchi di opportunità.", en: "Adds 5 feet to your reach when attacking with it and for Opportunity Attacks." },
    thrown: { it: "Puoi lanciare l'arma per un attacco a distanza ed estrarla come parte dell'attacco. Se è da mischia, usi lo stesso modificatore che useresti in mischia.", en: "You can throw the weapon for a ranged attack and draw it as part of that attack. A Melee weapon uses the same modifier as a melee attack." },
    two_handed: { it: "Richiede due mani per attaccare.", en: "Requires two hands to attack." },
    versatile: { it: "Si usa a una o a due mani; il danno tra parentesi vale se la impugni a due mani per un attacco da mischia.", en: "Can be used with one or two hands; the damage in parentheses applies when wielded two-handed in melee." },
  },
  masteries: {
    cleave: { it: "Se colpisci una creatura in mischia, puoi attaccare una seconda creatura entro 5 piedi dalla prima e alla tua portata. Se colpisce, subisce il danno dell'arma senza il modificatore (salvo negativo). Una volta per turno.", en: "On a melee hit, you can attack a second creature within 5 feet of the first and within your reach. On a hit it takes the weapon's damage without your ability modifier (unless negative). Once per turn." },
    graze: { it: "Se manchi il bersaglio, gli infliggi danni pari al modificatore usato per l'attacco, dello stesso tipo dell'arma.", en: "If you miss, the target takes damage equal to the ability modifier you used for the attack, of the weapon's damage type." },
    nick: { it: "L'attacco extra della proprietà Leggera si può fare con l'azione Attacco invece che con un'azione bonus. Una volta per turno.", en: "The extra attack of the Light property can be made as part of the Attack action instead of as a Bonus Action. Once per turn." },
    push: { it: "Se colpisci una creatura Grande o più piccola, puoi spingerla fino a 10 piedi in linea retta lontano da te.", en: "On a hit against a Large or smaller creature, you can push it up to 10 feet straight away from you." },
    sap: { it: "Se colpisci, il bersaglio ha Svantaggio al suo prossimo tiro per colpire prima dell'inizio del tuo prossimo turno.", en: "On a hit, the target has Disadvantage on its next attack roll before the start of your next turn." },
    slow: { it: "Se colpisci e infliggi danni, la Velocità del bersaglio cala di 10 piedi fino all'inizio del tuo prossimo turno (la riduzione non supera 10 piedi in totale).", en: "On a hit that deals damage, the target's Speed drops by 10 feet until the start of your next turn (the reduction never exceeds 10 feet)." },
    topple: { it: "Se colpisci, il bersaglio deve superare un tiro salvezza su Costituzione (CD 8 + modificatore dell'attacco + bonus di competenza) o cade a terra (condizione Prono).", en: "On a hit, the target must succeed on a Constitution saving throw (DC 8 + the attack's ability modifier + your Proficiency Bonus) or have the Prone condition." },
    vex: { it: "Se colpisci e infliggi danni, hai Vantaggio al tuo prossimo tiro per colpire contro quella creatura prima della fine del tuo prossimo turno.", en: "On a hit that deals damage, you have Advantage on your next attack roll against that creature before the end of your next turn." },
  },
  backgrounds: {
    acolyte: { it: "Una vita di servizio in un tempio o in una comunità religiosa.", en: "A life of service in a temple or religious community." },
    criminal: { it: "Hai vissuto di espedienti, furti e raggiri ai margini della legge.", en: "You got by on odd jobs, theft, and scams at the edge of the law." },
    sage: { it: "Anni di studio tra libri, archivi e maestri.", en: "Years of study among books, archives, and teachers." },
    soldier: { it: "Una vita tra i ranghi di un esercito o di una milizia, tra addestramento e battaglie.", en: "A life in the ranks of an army or militia, between training and battle." },
  },
  feats: {
    alert: { it: "Aggiungi il bonus di competenza ai tiri di iniziativa. Subito dopo aver tirato l'iniziativa puoi scambiare il risultato con quello di un alleato consenziente (non se uno dei due è incapacitato).", en: "Add your Proficiency Bonus to Initiative rolls. Right after rolling Initiative, you can swap your result with a willing ally's (not if either of you is Incapacitated)." },
    magic_initiate: { it: "Impari due trucchetti e un incantesimo di 1° livello dalla lista di chierico, druido o mago (caratteristica da incantatore: Intelligenza, Saggezza o Carisma, a scelta). L'incantesimo è sempre preparato e lo lanci una volta gratis per riposo lungo, oppure con uno slot. A ogni livello puoi cambiarne uno. Ripetibile, con una lista diversa.", en: "You learn two cantrips and one 1st-level spell from the Cleric, Druid, or Wizard list (spellcasting ability: Intelligence, Wisdom, or Charisma, your choice). The spell is always prepared and you cast it once for free per Long Rest, or with a spell slot. You can swap one when you gain a level. Repeatable, with a different list." },
    savage_attacker: { it: "Una volta per turno, quando colpisci con un'arma, tira due volte i danni dell'arma e usa il risultato che preferisci.", en: "Once per turn when you hit with a weapon, roll the weapon's damage dice twice and use either result." },
    skilled: { it: "Ottieni competenza in tre abilità o strumenti a scelta. Ripetibile.", en: "You gain proficiency in any three skills or tools of your choice. Repeatable." },
    ability_score_improvement: { it: "Aumenta una caratteristica di 2, oppure due caratteristiche di 1, fino a un massimo di 20. Ripetibile.", en: "Increase one ability score by 2, or two ability scores by 1, up to a maximum of 20. Repeatable." },
    grappler: { it: "Forza o Destrezza +1 (max 20). Con un colpo senz'armi nell'azione Attacco puoi infliggere danni e afferrare insieme (una volta per turno). Hai Vantaggio ai tiri per colpire contro chi stai afferrando, e spostarlo non costa movimento extra se è di taglia pari o inferiore alla tua.", en: "Strength or Dexterity +1 (max 20). When you hit with an Unarmed Strike during the Attack action, you can deal damage and grapple at once (once per turn). You have Advantage on attacks against a creature you're grappling, and moving it costs no extra movement if it's your size or smaller." },
    archery: { it: "+2 ai tiri per colpire con le armi a distanza.", en: "+2 to attack rolls with Ranged weapons." },
    defense: { it: "+1 alla Classe Armatura finché indossi un'armatura leggera, media o pesante.", en: "+1 to Armor Class while wearing Light, Medium, or Heavy armor." },
    great_weapon_fighting: { it: "Quando tiri i danni di un attacco da mischia con un'arma impugnata a due mani (proprietà A due mani o Versatile), un 1 o un 2 conta come 3.", en: "When you roll damage for a melee attack with a weapon held in two hands (Two-Handed or Versatile), a 1 or 2 on a damage die counts as a 3." },
    two_weapon_fighting: { it: "Quando fai l'attacco extra con un'arma Leggera, aggiungi il modificatore di caratteristica ai danni (se non è già stato aggiunto).", en: "When you make the extra attack with a Light weapon, add your ability modifier to its damage (if not already added)." },
    boon_of_combat_prowess: { it: "+1 a una caratteristica (max 30). Mira impareggiabile: quando manchi con un tiro per colpire puoi colpire comunque; non puoi riusarlo fino all'inizio del tuo prossimo turno.", en: "+1 to one ability score (max 30). Peerless Aim: when you miss with an attack roll, you can hit instead; you can't use this again until the start of your next turn." },
    boon_of_dimensional_travel: { it: "+1 a una caratteristica (max 30). Dopo l'azione Attacco o Magia puoi teletrasportarti fino a 9 metri (30 piedi) in uno spazio libero che vedi.", en: "+1 to one ability score (max 30). After taking the Attack or Magic action, you can teleport up to 30 feet to an unoccupied space you can see." },
    boon_of_fate: { it: "+1 a una caratteristica (max 30). Quando tu o una creatura entro 18 metri (60 piedi) fate una prova con d20, puoi tirare 2d4 e applicare il risultato come bonus o penalità. Si ricarica quando tiri l'iniziativa o con un riposo breve o lungo.", en: "+1 to one ability score (max 30). When you or another creature within 60 feet makes a D20 Test, you can roll 2d4 and apply the result as a bonus or penalty. It recharges when you roll Initiative or finish a Short or Long Rest." },
    boon_of_irresistible_offense: { it: "Forza o Destrezza +1 (max 30). I tuoi danni contundenti, perforanti e taglienti ignorano la resistenza. Con un 20 al tiro per colpire infliggi danni extra pari al punteggio aumentato, dello stesso tipo dell'attacco.", en: "Strength or Dexterity +1 (max 30). Your Bludgeoning, Piercing, and Slashing damage ignores Resistance. On a 20 on the attack roll, you deal extra damage equal to the increased score, of the attack's type." },
    boon_of_spell_recall: { it: "Intelligenza, Saggezza o Carisma +1 (max 30). Quando lanci un incantesimo con uno slot di livello da 1 a 4, tira 1d4: se esce il livello dello slot, non viene consumato.", en: "Intelligence, Wisdom, or Charisma +1 (max 30). When you cast a spell with a level 1-4 slot, roll 1d4: if the result equals the slot's level, the slot isn't expended." },
    boon_of_the_night_spirit: { it: "+1 a una caratteristica (max 30). In oscurità o luce fioca puoi diventare invisibile come azione bonus (finisce quando agisci) e hai resistenza a tutti i danni tranne psichici e radiosi.", en: "+1 to one ability score (max 30). In Dim Light or Darkness you can become Invisible as a Bonus Action (it ends when you act), and you have Resistance to all damage except Psychic and Radiant." },
    boon_of_truesight: { it: "+1 a una caratteristica (max 30). Hai vista pura entro 18 metri (60 piedi).", en: "+1 to one ability score (max 30). You have Truesight out to 60 feet." },
  },
  tools: {
    alchemists_supplies: { it: "Identificare una sostanza (CD 15) o accendere un fuoco (CD 15).", en: "Identify a substance (DC 15) or start a fire (DC 15)." },
    brewers_supplies: { it: "Riconoscere una bevanda avvelenata (CD 15) o un alcolico (CD 10).", en: "Detect a poisoned drink (DC 15) or identify alcohol (DC 10)." },
    calligraphers_supplies: { it: "Scrivere con svolazzi elaborati che proteggono dalle falsificazioni (CD 15).", en: "Write with elaborate flourishes that guard against forgery (DC 15)." },
    carpenters_tools: { it: "Sigillare o forzare una porta o un contenitore (CD 20).", en: "Seal or pry open a door or container (DC 20)." },
    cartographers_tools: { it: "Disegnare la mappa di una piccola zona (CD 15).", en: "Draft a map of a small area (DC 15)." },
    cobblers_tools: { it: "Modificare le calzature perché chi le indossa abbia Vantaggio alla prossima prova di Destrezza (Acrobazia) (CD 10).", en: "Modify footwear so the wearer has Advantage on their next Dexterity (Acrobatics) check (DC 10)." },
    cooks_utensils: { it: "Migliorare il sapore del cibo (CD 10) o riconoscere cibo avariato o avvelenato (CD 15).", en: "Improve food's flavor (DC 10) or detect spoiled or poisoned food (DC 15)." },
    glassblowers_tools: { it: "Capire cosa ha contenuto un oggetto di vetro nelle ultime 24 ore (CD 15).", en: "Tell what a glass object has held in the past 24 hours (DC 15)." },
    jewelers_tools: { it: "Stimare il valore di una gemma (CD 15).", en: "Appraise a gem's value (DC 15)." },
    leatherworkers_tools: { it: "Aggiungere un motivo decorativo a un oggetto di cuoio (CD 10).", en: "Add a design to a leather item (DC 10)." },
    masons_tools: { it: "Scalpellare un simbolo o un foro nella pietra (CD 10).", en: "Chisel a symbol or hole in stone (DC 10)." },
    painters_supplies: { it: "Dipingere un'immagine riconoscibile di qualcosa che hai visto (CD 10).", en: "Paint a recognizable image of something you've seen (DC 10)." },
    potters_tools: { it: "Capire cosa ha contenuto un oggetto di ceramica nelle ultime 24 ore (CD 15).", en: "Tell what a ceramic object has held in the past 24 hours (DC 15)." },
    smiths_tools: { it: "Forzare una porta o un contenitore (CD 20).", en: "Pry open a door or container (DC 20)." },
    tinkers_tools: { it: "Assemblare un oggetto Minuscolo con materiali di recupero, che si smonta dopo 1 minuto (CD 20).", en: "Assemble a Tiny item from scraps; it falls apart after 1 minute (DC 20)." },
    weavers_tools: { it: "Rammendare uno strappo negli abiti (CD 10) o cucire un piccolo disegno (CD 10).", en: "Mend a tear in clothing (DC 10) or sew a Tiny design (DC 10)." },
    woodcarvers_tools: { it: "Intagliare un motivo nel legno (CD 10).", en: "Carve a pattern in wood (DC 10)." },
    disguise_kit: { it: "Truccarsi (CD 10).", en: "Apply makeup (DC 10)." },
    forgery_kit: { it: "Imitare fino a 10 parole della scrittura di un'altra persona (CD 15) o duplicare un sigillo di ceralacca (CD 20).", en: "Mimic 10 or fewer words of someone else's handwriting (DC 15) or duplicate a wax seal (DC 20)." },
    herbalism_kit: { it: "Identificare una pianta (CD 10).", en: "Identify a plant (DC 10)." },
    navigators_tools: { it: "Tracciare una rotta (CD 10) o stabilire la posizione osservando le stelle (CD 15).", en: "Plot a course (DC 10) or fix your position by the stars (DC 15)." },
    poisoners_kit: { it: "Riconoscere un oggetto avvelenato (CD 10).", en: "Detect a poisoned object (DC 10)." },
    thieves_tools: { it: "Scassinare una serratura (CD 15) o disattivare una trappola (CD 15).", en: "Pick a lock (DC 15) or disarm a trap (DC 15)." },
  },
};

// Giochi e strumenti musicali: un testo per gruppo (ognuno richiede una competenza a parte)
export const GROUP_DESCRIPTIONS: Record<string, Desc> = {
  gaming: { it: "Capire se qualcuno bara (CD 10) o vincere la partita (CD 20). Ogni gioco richiede una competenza a parte.", en: "Discern whether someone is cheating (DC 10) or win the game (DC 20). Each game needs its own proficiency." },
  musical: { it: "Suonare un brano conosciuto (CD 10) o improvvisare (CD 15). Ogni strumento richiede una competenza a parte.", en: "Play a known tune (DC 10) or improvise a song (DC 15). Each instrument needs its own proficiency." },
};
