// Abbinamento dei nomi degli oggetti magici EN → IT (verificato a mano sui due PDF).
// Non si può fare in automatico: l'ordine alfabetico cambia da una lingua all'altra e molti oggetti hanno lo stesso tipo e la stessa rarità.
// Lo script ricontrolla ogni coppia (categoria, rarità, sintonia, dadi e CD del testo) e si ferma se qualcosa non torna.
export const MAGIC_NAMES = `
Adamantine Armor = Armatura adamantina
Ammunition, +1, +2, or +3 = Munizione +1, +2 o +3
Ammunition of Slaying = Munizione assassina
Amulet of Health = Amuleto della salute
Amulet of Proof against Detection and Location = Amuleto anti-individuazione e localizzazione
Amulet of the Planes = Amuleto dei piani
Animated Shield = Scudo animato
Apparatus of the Crab = Apparatus del granchio
Armor, +1, +2, or +3 = Armatura +1, +2 o +3
Armor of Invulnerability = Armatura dell'invulnerabilità
Armor of Resistance = Armatura della resistenza
Armor of Vulnerability = Armatura della vulnerabilità
Arrow-Catching Shield = Scudo catturafrecce
Bag of Beans = Borsa dei fagioli magici
Bag of Devouring = Borsa divorante
Bag of Holding = Borsa conservante
Bag of Tricks = Borsa dei trucchi
Bead of Force = Biglia di forza
Bead of Nourishment = Perla nutriente
Belt of Dwarvenkind = Cintura nanica
Belt of Giant Strength = Cintura della forza dei giganti
Berserker Axe = Ascia del berserker
Boots of Elvenkind = Stivali elfici
Boots of Levitation = Stivali della levitazione
Boots of Speed = Stivali della velocità
Boots of Striding and Springing = Stivali molleggiati
Boots of the Winterlands = Stivali dell'inverno
Bowl of Commanding Water Elementals = Boccia del comando degli elementali dell'acqua
Bracers of Archery = Bracciali dell'arciere
Bracers of Defense = Bracciali della difesa
Brazier of Commanding Fire Elementals = Braciere del comando degli elementali del fuoco
Brooch of Shielding = Fermaglio dello scudo
Broom of Flying = Scopa volante
Candle of Invocation = Candela dell'invocazione
Cape of the Mountebank = Cappa del saltimbanco
Carpet of Flying = Tappeto volante
Censer of Controlling Air Elementals = Incensiere del controllo degli elementali dell'aria
Chime of Opening = Campana dell'apertura
Circlet of Blasting = Diadema incandescente
Cloak of Arachnida = Mantello dell'aracnide
Cloak of Displacement = Mantello distorcente
Cloak of Elvenkind = Mantello elfico
Cloak of Invisibility = Mantello dell'invisibilità
Cloak of Protection = Mantello della protezione
Cloak of the Bat = Mantello del pipistrello
Cloak of the Manta Ray = Mantello della manta
Crystal Ball = Sfera di cristallo
Crystal Ball of Mind Reading = Sfera di cristallo della lettura del pensiero
Crystal Ball of Telepathy = Sfera di cristallo della telepatia
Crystal Ball of True Seeing = Sfera di cristallo della visione del vero
Cube of Force = Cubo di forza
Cubic Gate = Cubo dei portali
Dagger of Venom = Pugnale avvelenato
Dancing Sword = Spada danzante
Decanter of Endless Water = Caraffa dell'acqua eterna
Deck of Illusions = Mazzo delle illusioni
Defender = Difensiva
Demon Armor = Armatura demoniaca
Dimensional Shackles = Manette dimensionali
Dragon Orb = Sfera del drago
Dragon Scale Mail = Corazza di scaglie di drago
Dragon Slayer = Ammazzadraghi
Dust of Disappearance = Polvere dell'invisibilità
Dust of Dryness = Polvere prosciugante
Dust of Sneezing and Choking = Polvere dello starnuto e del soffocamento
Dwarven Plate = Armatura nanica
Dwarven Thrower = Martello nanico da lancio
Efficient Quiver = Faretra efficiente
Efreeti Bottle = Bottiglia dell'efreeti
Elemental Gem = Gemma elementale
Elixir of Health = Elisir della salute
Elven Chain = Giaco di maglia elfico
Energy Bow = Arco energetico
Eversmoking Bottle = Bottiglia del fumo perenne
Eyes of Charming = Lenti dello charme
Eyes of Minute Seeing = Lenti della visione dettagliata
Eyes of the Eagle = Lenti dell'aquila
Feather Token = Piuma di Quaal
Figurine of Wondrous Power = Statuina del potere meraviglioso
Flame Tongue = Lingua di fiamme
Folding Boat = Barca pieghevole
Frost Brand = Spadone del gelo
Gauntlets of Ogre Power = Guanti del potere orchesco
Gem of Brightness = Gemma della luminosità
Gem of Seeing = Gemma della visione
Giant Slayer = Ammazzagiganti
Glamoured Studded Leather = Armatura di cuoio borchiato incantata
Gloves of Missile Snaring = Guanti catturaproiettili
Gloves of Swimming and Climbing = Guanti del nuotare e scalare
Gloves of Thievery = Guanti ladreschi
Goggles of Night = Occhiali della notte
Hammer of Thunderbolts = Martello dei fulmini
Handy Haversack = Zainetto pratico
Hat of Disguise = Cappello del camuffamento
Hat of Many Spells = Cappello dei molti incantesimi
Headband of Intellect = Fascia dell'intelletto
Helm of Brilliance = Elmo della luminosità
Helm of Comprehending Languages = Elmo della comprensione dei linguaggi
Helm of Telepathy = Elmo della telepatia
Helm of Teleportation = Elmo del teletrasporto
Holy Avenger = Sacro vendicatore
Horn of Blasting = Corno della distruzione
Horn of Valhalla = Corno del Valhalla
Horseshoes of a Zephyr = Ferri dello zefiro
Horseshoes of Speed = Ferri della velocità
Immovable Rod = Verga inamovibile
Instant Fortress = Fortezza istantanea
Ioun Stone = Pietra di Ioun
Iron Bands = Fasce metalliche
Iron Flask = Ampolla di ferro
Javelin of Lightning = Giavellotto del fulmine
Lantern of Revealing = Lanterna della rivelazione
Luck Blade = Lama della fortuna
Mace of Disruption = Mazza della distruzione
Mace of Smiting = Mazza della punizione
Mace of Terror = Mazza del terrore
Mantle of Spell Resistance = Mantello della resistenza agli incantesimi
Manual of Bodily Health = Manuale della salute
Manual of Gainful Exercise = Manuale dell'esercizio fisico
Manual of Golems = Manuale dei golem
Manual of Quickness of Action = Manuale della velocità di azione
Marvelous Pigments = Pigmenti meravigliosi
Medallion of Thoughts = Medaglione dei pensieri
Mirror of Life Trapping = Specchio imprigionante
Mithral Armor = Armatura in mithral
Mysterious Deck = Mazzo delle meraviglie
Necklace of Adaptation = Collana dell'adattamento
Necklace of Fireballs = Collana delle palle di fuoco
Necklace of Prayer Beads = Collana del rosario
Nine Lives Stealer = Ruba nove vite
Oathbow = Arco del giuramento
Oil of Etherealness = Olio della forma eterea
Oil of Sharpness = Olio dell'affilatura
Oil of Slipperiness = Olio della scivolosità
Pearl of Power = Perla del potere
Periapt of Health = Talismano della salute
Periapt of Proof against Poison = Talismano anti-veleno
Periapt of Wound Closure = Talismano della rimarginazione
Philter of Love = Filtro d'amore
Pipes of Haunting = Flauto incantatore
Pipes of the Sewers = Flauto dei topi
Plate Armor of Etherealness = Armatura a piastre della forma eterea
Portable Hole = Buco portatile
Potion of Animal Friendship = Pozione di amicizia con gli animali
Potion of Clairvoyance = Pozione di chiaroveggenza
Potion of Climbing = Pozione di scalare
Potion of Diminution = Pozione di diminuzione
Potion of Flying = Pozione di volare
Potion of Gaseous Form = Pozione della forma gassosa
Potion of Giant Strength = Pozione della forza dei giganti
Potion of Growth = Pozione di crescita
Potions of Healing = Pozioni di guarigione
Potion of Heroism = Pozione di eroismo
Potion of Invisibility = Pozione di invisibilità
Potion of Invulnerability = Pozione di invulnerabilità
Potion of Longevity = Pozione di longevità
Potion of Mind Reading = Pozione di lettura della mente
Potion of Poison = Pozione velenosa
Potion of Resistance = Pozione di resistenza
Potion of Speed = Pozione di velocità
Potion of Vitality = Pozione di vitalità
Potion of Water Breathing = Pozione del respirare sott'acqua
Quarterstaff of the Acrobat = Bastone ferrato dell'acrobata
Ring of Animal Influence = Anello di influenza sugli animali
Ring of Djinni Summoning = Anello di richiamo del djinni
Ring of Elemental Command = Anello del comando degli elementali
Ring of Evasion = Anello di eludere
Ring of Feather Falling = Anello della caduta morbida
Ring of Free Action = Anello della libertà di azione
Ring of Invisibility = Anello di invisibilità
Ring of Jumping = Anello del saltare
Ring of Mind Shielding = Anello di scudo mentale
Ring of Protection = Anello di protezione
Ring of Regeneration = Anello di rigenerazione
Ring of Resistance = Anello di resistenza
Ring of Shooting Stars = Anello di stelle cadenti
Ring of Spell Storing = Anello accumula incantesimi
Ring of Spell Turning = Anello rifletti incantesimo
Ring of Swimming = Anello del nuotare
Ring of Telekinesis = Anello di telecinesi
Ring of the Ram = Anello dell'ariete
Ring of Three Wishes = Anello dei tre desideri
Ring of Warmth = Anello del calore
Ring of Water Walking = Anello del camminare sull'acqua
Ring of X-ray Vision = Anello della vista a raggi X
Robe of Eyes = Tunica degli occhi
Robe of Scintillating Colors = Tunica dei colori scintillanti
Robe of Stars = Tunica delle stelle
Robe of the Archmagi = Tunica dell'arcimago
Robe of Useful Items = Tunica degli oggetti utili
Rod of Absorption = Verga dell'assorbimento
Rod of Alertness = Verga dell'allerta
Rod of Lordly Might = Verga della potenza divina
Rod of Resurrection = Verga della resurrezione
Rod of Rulership = Verga della sovranità
Rod of Security = Verga della sicurezza
Rope of Climbing = Corda per scalare
Rope of Entanglement = Corda intralciante
Scarab of Protection = Scarabeo di protezione
Scimitar of Speed = Scimitarra della velocità
Sending Stones = Pietre parlanti
Sentinel Shield = Scudo sentinella
Shield, +1, +2, or +3 = Scudo +1, +2 o +3
Shield of Missile Attraction = Scudo attiraproiettili
Shield of the Cavalier = Scudo del cavaliere
Slippers of Spider Climbing = Pantofole del ragno
Sovereign Glue = Colla meravigliosa
Spellguard Shield = Scudo anti-incantesimi
Spell Scroll = Pergamena magica
Sphere of Annihilation = Sfera annientatrice
Staff of Charming = Bastone dello charme
Staff of Fire = Bastone del fuoco
Staff of Frost = Bastone del gelo
Staff of Healing = Bastone della guarigione
Staff of Power = Bastone del potere
Staff of Striking = Bastone del colpo possente
Staff of Swarming Insects = Bastone dello sciame di insetti
Staff of the Magi = Bastone dei magi
Staff of the Python = Bastone del pitone
Staff of the Woodlands = Bastone dei boschi
Staff of Thunder and Lightning = Bastone dei tuoni e fulmini
Staff of Withering = Bastone del deperimento
Stone of Controlling Earth Elementals = Pietra del controllo degli elementali della terra
Stone of Good Luck (Luckstone) = Pietra della buona fortuna (pietrafortuna)
Sun Blade = Lama del sole
Sword of Life Stealing = Spada del furto vitale
Sword of Sharpness = Spada affilata
Sword of Wounding = Spada del ferimento
Talisman of Pure Good = Talismano del bene puro
Talisman of the Sphere = Talismano della sfera
Talisman of Ultimate Evil = Talismano del male estremo
Thunderous Greatclub = Randello pesante del tuono
Tome of Clear Thought = Tomo del nitido pensiero
Tome of Leadership and Influence = Tomo del comando e dell'influenza
Tome of Understanding = Tomo della comprensione
Trident of Fish Command = Tridente del comando dei pesci
Universal Solvent = Solvente universale
Vicious Weapon = Arma spietata
Vorpal Sword = Spada vorpal
Wand of Binding = Bacchetta del legame
Wand of Enemy Detection = Bacchetta di individuazione dei nemici
Wand of Fear = Bacchetta della paura
Wand of Fireballs = Bacchetta delle palle di fuoco
Wand of Lightning Bolts = Bacchetta dei fulmini
Wand of Magic Detection = Bacchetta di individuazione del magico
Wand of Magic Missiles = Bacchetta di dardi incantati
Wand of Paralysis = Bacchetta della paralisi
Wand of Polymorph = Bacchetta della metamorfosi
Wand of Secrets = Bacchetta dei segreti
Wand of the War Mage, +1, +2, or +3 = Bacchetta del mago da guerra +1, +2 o +3
Wand of Web = Bacchetta della ragnatela
Wand of Wonder = Bacchetta delle meraviglie
Weapon, +1, +2, or +3 = Arma +1, +2 o +3
Weapon of Warning = Arma dell'avvertimento
Well of Many Worlds = Pozzo dei mondi
Wind Fan = Ventaglio
Winged Boots = Stivali alati
Wings of Flying = Ali del volo
`.trim().split("\n").map((l) => l.split(" = ") as [string, string]);
